### ISSUE TITLE
Saving data in eqidistant timeintervalls

### ISSUE THREAD

**Issue by covim** [ioBroker/ioBroker.history#112]
Would it be possible to add an option to save datapoints in equidistant timeintervall. For example to store the value of an object every 5 minutes. when having different logging objects all should be stored at the same absolute time.

**Comment by Apollon77** [comment]
We will not implement this because it is too special. You can basically use the blocking feature, but this will not log it "on a special timepoint" (e.g. 00:00 or such). For this the best practice is to have a small Javascript and an own state and enable logging for this
