### ISSUE TITLE
Feature-Request: Please add Data-Editor for history

### ISSUE THREAD

**Issue by Homoran** [ioBroker/ioBroker.history#127]
as discussed here:
https://forum.iobroker.net/topic/48105/history-editor
it would be fine if the user would have an easy way to edit the data.

(is there no label - for feature request?)

**Comment by Diginix** [comment]
@Draexl 
<img width="653" alt="image" src="https://user-images.githubusercontent.com/39678667/160595241-707005f1-3daf-467d-be63-9637d4aeabd7.png">

**Comment by Draexl** [comment]
Unfortunately I don't have this button. I've uninstalled and reinstalled the adapter
![Bildschirmfoto 2022-03-29 um 14 07 08](https://user-images.githubusercontent.com/86128006/160607832-10e95a35-914c-4773-b680-b450a65eee85.png)
.

**Comment by Draexl** [comment]
Solved, I have to start with the expert view...

**Comment by Apollon77** [comment]
So in fact Issue solved?

**Comment by Draexl** [comment]
Yes
