### ISSUE TITLE
Werte werden unerlaubt und nachträglich reduziert

### ISSUE THREAD

**Issue by nicomania** [ioBroker/ioBroker.history#132]
Hallo,

ich benutze den history Adapter, um mehrere Datenpunkte in einem Einzigen zu schreiben, damit ich diese Werte dann in einem Balkendiagramm gemeinsam darstellen kann. Dazu lasse ich ein Skript die Werte im Abstand von 600ms in diesen Datenpunkt schreiben. Dieser leider unschöne workaround ist nötig, weil sämtliche chart Adapter sowas nur per history darstellen können.

Das Schreiben der insgesamt 8 Werte funktioniert auch und ich kann den Schreibprozess live im Reiter "Verlaufsdaten" sehen. Doch nach wenigen Sekunden beginnt der Adapter die Datenpunkte automatisch wieder zu löschen und einige Werte verschwinden wie von Zauberhand. 

Soll das ein feature sein? Falls ja, nach welchen Gesichtspunkten wird da gelöscht? Kann man das abschalten?
Ich dachte das Konzept dieses Adapters sei die alleinige Speicherung von Daten und nicht das Nachbehandeln Selbiger. Ich würde mir zumindest eine checkbox zum Abschalten dieses Verhaltens wünschen. Ist das möglich?

Viele Grüße

**Comment by Apollon77** [comment]
EIn Log als Screenshot ... und dann noch nur ein paar Zeilen sind keistens nicht so hilfreich ... Bitte sei etwas mehr "verbose" und Textuell 

Am Ende sid es jetzt hier ggf viele Dinge die hier reinspielen. Die Frage #1 ist ja "werden die Daten korrekt gespeichert" und die zweite ist "was zeigt Admin an und warum". Und daher lass das mal trennen. Stehen alle erwarteten Werte innden json Files? Wenn ja ist schonmal alles gespeichert. Dann istdie Frage "was zeigt Adminin dr Tanelle an" ... hier Fehlet mir auch ein Screenshot von den EInstellungen dort

**Comment by nicomania** [comment]
[iobroker.current.log](https://github.com/ioBroker/ioBroker.history/files/7299884/iobroker.current.log)
Hier eine Log mit provoziertem Schreiben. Diesmal sind **alle** Einträge wieder verschwunden. Ich sehe nur in der der Tabelle des Datenpunkts wie die Werte rein kommen und dann wieder weg sind. 

![image](https://user-images.githubusercontent.com/35151132/136340753-7b9c473a-24a8-4ee7-b929-f46e6c8852f9.png)
Hier die Einstellungen des Adapters. Für alles andere brauche ich genauere Instruktionen.

**Comment by Apollon77** [comment]
Will be fixed in next version Together with a new admin version
