### ISSUE TITLE
Missing translations in Admin 5 UI

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.history#137]
**Describe the bug**  

Missing translations in Admin 5 UI

**To Reproduce**  

- Install adapter
- Change language in system settings (e.g. German)

**Expected behavior**  

Show translated texts.

**Screenshots & Logfiles**  

<img width="762" alt="Screenshot 2021-11-10 at 15 48 30" src="https://user-images.githubusercontent.com/1959049/141134947-935b9d42-e749-42de-be38-e9b9978e3487.png">

**Versions:**  

 - Adapter version: 1.9.13

**i18n is ignored by npm**

https://github.com/ioBroker/ioBroker.history/blob/8eda47b10d00b5fb2e8617001d05908fd65c80cf/.npmignore#L9

**Comment by Apollon77** [comment]
Thank you, next version
