### ISSUE TITLE
Too much information in version field

### ISSUE THREAD

**Issue by TA2k** [ioBroker/ioBroker.history#145]
<img width="1724" alt="image" src="https://user-images.githubusercontent.com/1307684/148904432-c2831aee-aa77-4525-83a0-a7f563393a9b.png">

**Comment by Apollon77** [comment]
This is, if, an admin issue in displaying changelog ... maybe casued by  the > in the news text in Admin 4 UI ... this is kind of a known issue in Amdin  ... Does it also happen with Admin5 UI?

**Comment by TA2k** [comment]
Its only admin 4 UI

**Comment by Apollon77** [comment]
The I would not invest time to try to fix the news entry ... do the update and effect is gone :-))

**Comment by TA2k** [comment]
Ok but only as information the update button for manual update this package is also gone

**Comment by Apollon77** [comment]
Yes, this exactly is the issue in Admin 4 with this ... I can see if I find time to cleanup the next text

**Comment by Apollon77** [comment]
reload repo this evening ... i updated io-paxkage news
