### ISSUE TITLE
Cannot find search "custom" in "system"

### ISSUE THREAD

**Issue by Kopierwichtel** [ioBroker/ioBroker.history#161]
With the log i find the following error when starting the adapter:

Cannot find search "custom" in "system"

**To Reproduce**  
restart the adapter

**Expected behavior**  
there should be no error

**Screenshots & Logfiles**  
e.g. line 2509

**Versions:**  
 - Adapter version: 1.11.0
 - JS-Controller version: 3.3.22
 - Node version: v14.19.0
 - Operating system: linux
 - repository: http://iobroker.live/repo/sources-dist-latest.json

**Additional context**  
I'm using iobroker with docker buanet image v6.0.0 on a synology NAS
[history.zip](https://github.com/ioBroker/ioBroker.history/files/8140444/history.zip)

**Comment by Apollon77** [comment]
Please execute "iob setup first" ... should be fixed afterwards

**Comment by Kopierwichtel** [comment]
> Please execute "iob setup first" ... should be fixed afterwards

Can you give me a hint how to execute it? Thx

**Comment by Apollon77** [comment]
Using a "ssh shell" on your iobroker host

**Comment by Kopierwichtel** [comment]
I think i got it executed. I got this return message:

![2022-02-25 16_50_43-DS2413_1 - Synology DiskStation](https://user-images.githubusercontent.com/4805131/155745715-e24d8450-ed66-4faa-9df3-6de252dfd26a.jpg)

Will check if the issue still exists

**Comment by Apollon77** [comment]
Output is exactly the wanted one :-)

**Comment by Kopierwichtel** [comment]
This ticket can be closed. The error is not appearing anymore.

Suddenly the execution deleted my SSL certificates. Fixing this was quite a challenge because just pasting the keys into the the corresponding fields is not working. The certs are considered invalid, but in fact they are valid. But now everything is working again

**Comment by Apollon77** [comment]
This certificate issue should be fixed in js.controller 4.0.15
