### ISSUE TITLE
History is not properly written (after a adapter restart?)

### ISSUE THREAD

**Issue by Kopierwichtel** [ioBroker/ioBroker.history#162]
After the latest updates of history i have the issue, that after a restart of the adapter (or the docker container) the history is no longer written properly. When checking the objects the history setting are still there. When viewing the histroy tab the new values keep coming, but then get "deleted" again.

Additionally existing history data is not shown properly: e.g. from 24th feb 13:52 the onwards the data is missing, but within the chart its shown

**To Reproduce**  
I made a clean install of my docker container and used a backup file from backitup.
Then i updated all adapters 
After a few days i noticed that the history is empty and charts e.g. in flot are empty
On a few objects i disabled the history and reactivated again. then the history is written again properly 

**Expected behavior**  
History is written properly after an adapter restart
History data is shown properly in the tab history data

**Screenshots & Logfiles**  
see attachments

**Versions:**  
 - Adapter version: 1.11.0
 - JS-Controller version: 3.3.22
 - Node version: v14.19.0
 - Operating system: linux
[Issue History.zip](h
![2022-02-25 12_01_32-objects - buanet-iobroker1](https://user-images.githubusercontent.com/4805131/155705381-67012ad7-2de5-4a67-bb29-b201c47a0aec.jpg)
![2022-02-25 11_57_38-Window](https://user-images.githubusercontent.com/4805131/155705386-4bba42a2-82ef-4aee-a322-835df61ef6f5.jpg)
ttps://github.com/ioBroker/ioBroker.history/files/8140644/Issue.History.zip)

**Additional context**  
I'm using docker with image buanet v.6.0.0 on a synology NAS

And i have one question: which is the official stable repo. I'm using http://iobroker.live/repo/sources-dist-latest.json

**Comment by Kopierwichtel** [comment]
Pfa a video of the issue

[Issue History.zip](https://github.com/ioBroker/ioBroker.history/files/8140656/Issue.History.zip)

**Comment by Apollon77** [comment]
Can you please enable debug log for the history instance and do the same again and pot the debug log? Please note down the rough timepoints where the values "jumped".

**Comment by Kopierwichtel** [comment]
After fixing my other issue [(Cannot find search "custom" in "system" #161)](https://github.com/ioBroker/ioBroker.history/issues/161#issuecomment-1050983252) the main issue seems also to be fixed. The history is being written even after an adapter restart or a docker restart. 

The only issue that remains is the visual thing when viewing the history data. Like requested I will send the log by end of this day. Due to the restore the history is more or less empty.

**Comment by Apollon77** [comment]
@Kopierwichtel Any news for the log? :-)

**Comment by Kopierwichtel** [comment]
thx for the reminder, was no longer checking this because my system is now running as expected and didn't had to check the history anymore.

Neverheless the issue is still there, but only if there's a huge amount of data to load from history, e.g. for the last 24 hours (values are written every 10 sec). If i view the last hour everyting is fine


[history.zip](https://github.com/ioBroker/ioBroker.history/files/8357316/history.zip)
[history.log](https://github.com/ioBroker/ioBroker.history/files/8357320/history.log)
![history](https://user-images.githubusercontent.com/4805131/160276561-54c5ede1-2040-4edc-94ee-6c90e6b3e2e8.png)

**Comment by Apollon77** [comment]
Plese try GitHub version

**Comment by Kopierwichtel** [comment]
> Plese try GitHub version

Can you give me some more input hot to use/install it, thx

**Comment by Apollon77** [comment]
Sure, Admin - Adapters - enablce expertmode - klick the GitHub button that appears in iconlist (Custom install) and choose secodn tab in the popup ("Install from Github") Choose hoistory and do it ... Then pot manually restart history instance

**Comment by Kopierwichtel** [comment]
Looks like that its working now :-) But I noticed that only the last 500 entries are shown, not all entries of the last 24 hours. . Is this by intention? If so it would be nice to show a hint that only the last 500 entries will be shown.

But many thanks for fixing this. Now it makes more sence :-)

**Comment by Apollon77** [comment]
@Kopierwichtel After some internal discussions I will do the change differently ... this means that we will have a new version of history AND a new version of Admin ... them together will fix the issue ...  But just the hostory version will not ... so stay tuned please

**Comment by Apollon77** [comment]
Fix is in 2.0.0 together with a upcoming new Admin 5.3.8 ...

**Comment by Kopierwichtel** [comment]
Thanks for the update. I saw the new version of admin, but no version of History. Is this because I installed the test version from Git. Do i Have to uninstall the Git version and fetch the latest from the offical repo?

**Comment by Apollon77** [comment]
Please install from GitHub again. then History should be 2.0.0 ... Currently Alpha test
