### ISSUE TITLE
Zu viele Werte für einen Tag

### ISSUE THREAD

**Issue by Damrak2022** [ioBroker/ioBroker.history#167]
Withings schreit bei Activities unter Steps mehrere Werte an einem Tag
Wenn ich über das Zahnradsymbol auf die Einstellungen von Withings/Activities/Steps gehe, dann werden mir unter Verlaufsdaten mehrere Werte für einen Tag angezeigt. Ich möchte aber pro Tag nur einen Wert mit meinen insgesamt gegangenen Schritten haben, denn sonst schaffe ich es nicht ein vernünftiges Diagramm mit Flot zu erstellen.
Kann sich das bitte mal jemand anschauen, der Ahnung hat und nicht wie ich Anfänger ist.
Es wäre super wenn das gelöst werden könnte, da ich hier schon seit Wochen ruumprobiere.
<img width="1900" alt="Bildschirmfoto 2022-04-05 um 10 21 19" src="https://user-images.githubusercontent.com/101031627/161710854-9e207740-066f-4f8d-8cab-a8e46bb16dec.png">

**Comment by Apollon77** [comment]
Welche Einstellungen hast Du gewählt für den Datenpunkt?

**Comment by Damrak2022** [comment]
Ich nutzen den Datenpunkt Wihtings/Activities01/Steps

Am 5. Apr. 2022, 10:27 +0200 schrieb Ingo Fischer ***@***.***>:

**Comment by Diginix** [comment]
@Damrak2022 Die History Einstellungen des Objektes sind gemeint und gewünscht. Zu finden hier:
![image](https://user-images.githubusercontent.com/39678667/161744450-89fb061f-6ab9-4fba-92fa-a36a455c15a2.png)

**Comment by Damrak2022** [comment]
Sorry, hier kommt der richtige Screenshot
Am 5. Apr. 2022, 13:29 +0200 schrieb Diginix ***@***.***>:

**Comment by Damrak2022** [comment]
Hier nochmal ein zusätzlicher Screenshot wie das Diagramm in den Einstellungen des Datenpunktes aussieht Das sieht recht gut aus. Nur sobald ich es in Flot, oder im Marterialdesign Line Chart Adapter darstellen möchte sieht es auch die doppelten Werte chaotisch, unbrauchbar aus.
Am 6. Apr. 2022, 03:38 +0200 schrieb Foren ***@***.***>:

**Comment by Diginix** [comment]
@Damrak2022 Du scheinst immer per Email auf die GIT issues zu antworten. Das ist keine sinnvolle Bedienung denn man sieht deine Screenshots nicht bzw kommen die so gar nicht in GIT an. Geh bitte auf die Website und editiere deine Beiträge dort entsprechend. Dann kann man dir auch helfen.

**Comment by Damrak2022** [comment]
Okay, sorry, das habe ich nicht bedacht. Mache ich gleich
Am 6. Apr. 2022, 08:07 +0200 schrieb Diginix ***@***.***>:

**Comment by Damrak2022** [comment]
Sorry, das ich immer per Mail geantwortet hatte.
Jetzt hier noch mal die gewünschten Screenshots.
<img width="1920" alt="Bildschirmfoto 2022-04-06 um 03 38 07" src="https://user-images.githubusercontent.com/101031627/161907012-965ea3be-746d-4f7c-a594-ea8b6d9fa33c.png">
<img width="1915" alt="Bildschirmfoto 2022-04-06 um 05 01 33" src="https://user-images.githubusercontent.com/101031627/161907054-fbb49048-2d34-4b84-a262-747bae02dce5.png">

Wenn ich mir das Diagramm im Adapter selbst anschaue sieht das gut aus. Aber sobald ich es über Flot darstellen möchte, habe ich Chaos, da diese doppelten Werte die Probleme verursachen.

**Comment by Diginix** [comment]
Hm, bis auf die hohe Anzahl im RAM passt das mMn. Man könnte noch die Deltaprüfung auf 1 setzen. Dann sollte er erst bei Änderungungen des Wertes >=1 Werte speichern. Aber mit 0 und dem Haken "nur Änderungen" hätte es auch schon keine doppelten Werte pro Sekunde geben dürfen.

**Comment by Apollon77** [comment]
@Damrak2022 Bitte stelle History mal auf debug loglevel (Admin - expertenmodus aktivieren - Instanzen - history.0 aufklappen - Loglevel ändern). Und mal hier posten. Ich hab da eine Vermutung

**Comment by Damrak2022** [comment]
Ich hoffe, das ich das jetzt richtig gemacht habe:
`

Quelle | Zeit | debug | Nachricht
-- | -- | -- | --
history.0 | 2022-04-06 17:01:14.520 | debug | Min-Delta reached shelly.0.SHPLG-S#E423FA#1.temperatureC, last-value=34.37, new-value=34.42, ts=1649257274511
history.0 | 2022-04-06 17:01:11.526 | debug | value not changed shelly.0.SHPLG-S#E423FA#1.temperatureC, last-value=34.37, new-value=34.37, ts=1649257271518
history.0 | 2022-04-06 17:01:11.372 | debug | value not changed shelly.0.SHPLG-S#EA1400#1.temperatureC, last-value=35.01, new-value=35.01, ts=1649257271351
history.0 | 2022-04-06 17:01:10.535 | debug | value not changed shelly.0.SHPLG-S#E423FA#1.temperatureC, last-value=34.37, new-value=34.37, ts=1649257270514
history.0 | 2022-04-06 17:01:08.532 | debug | Min-Delta reached shelly.0.SHPLG-S#E423FA#1.temperatureC, last-value=34.48, new-value=34.37, ts=1649257268523
history.0 | 2022-04-06 17:01:08.415 | debug | Min-Delta reached rpi2.0.temperature.soc_temp, last-value=61.35, new-value=59.89, ts=1649257268390
history.0 | 2022-04-06 17:01:07.793 | debug | Min-Delta reached shelly.0.SHPLG-S#BBA82D#1.temperatureC, last-value=36.65, new-value=36.88, ts=1649257267775
history.0 | 2022-04-06 17:01:07.529 | debug | value not changed shelly.0.SHPLG-S#E423FA#1.temperatureC, last-value=34.48, new-value=34.48, ts=1649257267515
history.0 | 2022-04-06 17:01:05.533 | debug | value not changed shelly.0.SHPLG-S#E423FA#1.temperatureC, last-value=34.48, new-value=34.48, ts=1649257265515
history.0 | 2022-04-06 17:01:01.539 | debug | value not changed shelly.0.SHPLG-S#E423FA#1.temperatureC, last-value=34.48, new-value=34.48, ts=1649257261534
javascript.0 | 2022-04-06 17:01:00.118 | warn | script.js.common.NetzWerk.NetzwerkScan: no Data
history.0 | 2022-04-06 17:00:59.742 | debug | value not changed shelly.0.SHPLG-S#E423FA#1.temperatureC, last-value=34.48, new-value=34.48, ts=1649257259730
history.0 | 2022-04-06 17:00:58.567 | debug | Min-Delta reached shelly.0.SHPLG-S#E423FA#1.temperatureC, last-value=34.53, new-value=34.48, ts=1649257258549
history.0 | 2022-04-06 17:00:56.396 | debug | value not changed shelly.0.SHPLG-S#EA1400#1.temperatureC, last-value=35.01, new-value=35.01, ts=1649257256372
history.0 | 2022-04-06 17:00:55.533 | debug | value not changed shelly.0.SHPLG-S#E423FA#1.temperatureC, last-value=34.53, new-value=34.53, ts=1649257255514
history.0 | 2022-04-06 17:00:53.575 | debug | Min-Delta reached shelly.0.SHPLG-S#E423FA#1.temperatureC, last-value=34.37, new-value=34.53, ts=1649257253558
history.0 | 2022-04-06 17:00:49.532 | debug | value not changed shelly.0.SHPLG-S#E423FA#1.temperatureC, last-value=34.37, new-value=34.37, ts=1649257249514
history.0 | 2022-04-06 17:00:46.520 | debug | value not changed shelly.0.SHPLG-S#E423FA#1.temperatureC, last-value=34.37, new-value=34.37, ts=1649257246508
history.0 | 2022-04-06 17:00:41.372 | debug | Min-Delta reached shelly.0.SHPLG-S#EA1400#1.temperatureC, last-value=34.85, new-value=35.01, ts=1649257241354
history.0 | 2022-04-06 17:00:38.550 | debug | value not changed shelly.0.SHPLG-S#E423FA#1.temperatureC, last-value=34.37, new-value=34.37, ts=1649257238537
history.0 | 2022-04-06 17:00:37.792 | debug | Min-Delta reached shelly.0.SHPLG-S#BBA82D#1.temperatureC, last-value=36.57, new-value=36.65, ts=1649257237773
history.0 | 2022-04-06 17:00:37.533 | debug | value not changed shelly.0.SHPLG-S#E423FA#1.temperatureC, last-value=34.37, new-value=34.37, ts=1649257237513
host.homebridge | 2022-04-06 17:00:36.213 | info | instance system.adapter.daswetter.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
daswetter.0 | 2022-04-06 17:00:35.687 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): All data handled, adapter stopped until next scheduled moment
history.0 | 2022-04-06 17:00:35.519 | debug | Min-Delta reached shelly.0.SHPLG-S#E423FA#1.temperatureC, last-value=34.42, new-value=34.37, ts=1649257235510
host.homebridge | 2022-04-06 17:00:31.777 | info | instance system.adapter.ical.0 terminated with code 0 (NO_ERROR)
ical.0 | 2022-04-06 17:00:31.246 | info | Terminated (NO_ERROR): Without reason
daswetter.0 | 2022-04-06 17:00:31.137 | info | still wrong data structure from server received! repaired...
history.0 | 2022-04-06 17:00:29.196 | debug | Store the rest for withings.0.19990054.sleepSummary.series01.data.total_timeinbed
history.0 | 2022-04-06 17:00:29.194 | debug | Store the rest for withings.0.19990054.sleepSummary.series01.data.total_sleep_time
history.0 | 2022-04-06 17:00:29.193 | debug | Store the rest for withings.0.19990054.sleepSummary.series01.data.snoring
history.0 | 2022-04-06 17:00:29.191 | debug | Store the rest for withings.0.19990054.sleepSummary.series01.data.sleep_score
history.0 | 2022-04-06 17:00:29.189 | debug | Store the rest for withings.0.19990054.sleepSummary.series01.data.sleep_efficiency
history.0 | 2022-04-06 17:00:29.188 | debug | Store the rest for withings.0.19990054.sleepSummary.series01.data.hr_max
history.0 | 2022-04-06 17:00:29.186 | debug | Store the rest for withings.0.19990054.sleepSummary.series01.data.hr_average
history.0 | 2022-04-06 17:00:29.184 | debug | Store the rest for withings.0.19990054.sleep.model
history.0 | 2022-04-06 17:00:29.183 | debug | Store the rest for withings.0.19990054.activity.activities30.steps
history.0 | 2022-04-06 17:00:29.181 | debug | Store the rest for withings.0.19990054.activity.activities30.calories
history.0 | 2022-04-06 17:00:29.179 | debug | Store the rest for withings.0.19990054.activity.activities29.steps
history.0 | 2022-04-06 17:00:29.178 | debug | Store the rest for withings.0.19990054.activity.activities29.calories
history.0 | 2022-04-06 17:00:29.176 | debug | Store the rest for withings.0.19990054.activity.activities28.steps
history.0 | 2022-04-06 17:00:29.174 | debug | Store the rest for withings.0.19990054.activity.activities28.calories
history.0 | 2022-04-06 17:00:29.173 | debug | Store the rest for withings.0.19990054.activity.activities27.steps
history.0 | 2022-04-06 17:00:29.171 | debug | Store the rest for withings.0.19990054.activity.activities27.calories
history.0 | 2022-04-06 17:00:29.169 | debug | Store the rest for withings.0.19990054.activity.activities26.steps
history.0 | 2022-04-06 17:00:29.168 | debug | Store the rest for withings.0.19990054.activity.activities26.calories
history.0 | 2022-04-06 17:00:29.166 | debug | Store the rest for withings.0.19990054.activity.activities25.steps
history.0 | 2022-04-06 17:00:29.164 | debug | Store the rest for withings.0.19990054.activity.activities25.calories
history.0 | 2022-04-06 17:00:29.161 | debug | Store the rest for withings.0.19990054.activity.activities24.steps
history.0 | 2022-04-06 17:00:29.159 | debug | Store the rest for withings.0.19990054.activity.activities24.calories
history.0 | 2022-04-06 17:00:29.156 | debug | Store the rest for withings.0.19990054.activity.activities23.steps
history.0 | 2022-04-06 17:00:29.154 | debug | Store the rest for withings.0.19990054.activity.activities23.calories

`

**Comment by Apollon77** [comment]
Und du bekommst wirklich sekündliche Messwerte von den withings Datenpunkten?? Weil ich sehe nichts reinkommen an neuen Daten
