### ISSUE TITLE
missing data in visu

### ISSUE THREAD

**Issue by sv-hjo** [ioBroker/ioBroker.history#181]
I visu data from loxone (with this adapter) in HABpanel. 
For some values data is missing, there is only a line for many hours, then it goes on as if nothing happened.
In the object-data the values are available. The excel-export shows strange values.
![Einstellungen Adapter](https://user-images.githubusercontent.com/104100919/175806804-433de3e9-a68e-4a43-a48d-2cd75f7ecea9.jpg)
[Temperatur Überdachung_ value.csv](https://github.com/ioBroker/ioBroker.history/files/8986278/Temperatur.Uberdachung_.value.csv)
![Verlaufsdaten 250622](https://user-images.githubusercontent.com/104100919/175806807-d0fde346-d81f-4864-aaf2-ecfa31032d15.jpg)
![Verlaufsdaten](https://user-images.githubusercontent.com/104100919/175806808-02813e90-f241-47e4-9a18-65016ca81a5e.jpg)
![Visu Verläufe](https://user-images.githubusercontent.com/104100919/175806809-5eb6f54c-1364-4c53-bb5a-e55eb433b767.jpg)

**Comment by Apollon77** [comment]
Ok, questions:
Is the chart in Admin on that datapoint (Tab Diagram) complete if you select the same timeframe or is it looking the same?

When it looks the same then it seems more an issue with data query. To analyze this please set the loglevel of the Instance to "Debug" and enable the "enhanced logging " for such a datapoint in it's settings (not the default Instance settings!).

Then post that log please.

My Assumption is (because we had this case  some day ago) that you use "onCHange" as aggregation and set a limit e.g. 500 of datapoints that you want to get back, soyou only get those ... Then it would be an issue with the UI that sends the query

**Comment by sv-hjo** [comment]
![Einstellungen Datenpunkt](https://user-images.githubusercontent.com/104100919/175807455-1786bab4-bf94-4aa0-b790-75c83af7faaa.jpg)
onChange! 
diagram hangs - shows only 
![kein Diagramm](https://user-images.githubusercontent.com/104100919/175807551-63153ea6-5eb5-4f35-8d25-cdcd2b8edfcb.jpg)
running line.

**Comment by Apollon77** [comment]
WHich Admion version? ... Ok in fact please do the debug thing described above

**Comment by sv-hjo** [comment]
6.1.2 and even the new 6.1.5

**Comment by Apollon77** [comment]
Strange, ok for both:

Please enable debug on instance and datapoint as describe above and then

1.) Call via Admin
2.) Call via Visu and post debug log with both (and tell me when was what)

**Comment by sv-hjo** [comment]
[Log history 260622.txt](https://github.com/ioBroker/ioBroker.history/files/8986405/Log.history.260622.txt)

**Comment by Apollon77** [comment]
Also Admin Diagram sieht korrekt aus ... 
* er hat Zeitraum 24h angefordert, aber mit nem Step von 3600000 ... also ein Wert pro Stunde ... das ist bissl wenig  :-) wäre ggf ein Admin Issue wert :-)
* bekommen hat er 28 Werte, was mit den Settings auch ok ist
* Antwort hat er auch bekommen, warum Admin "hängt" -> Admin  Issue bitte anlegen, Danke

Ansonsten vermute ich das es daran liegt das Habpanel "keinen" count sendet, damit gilt der Default count von 500 ... ich überlege mir mal was

**Comment by Apollon77** [comment]
The new version will respect the limit of 2000 (or whatever is set) if no count is provided ... so should be 2000 then in your case ... That should be enough in your case. Please try
