### ISSUE TITLE
Minimal difference to last value

### ISSUE THREAD

**Issue by sv-hjo** [ioBroker/ioBroker.history#182]
![Verläufe 270622](https://user-images.githubusercontent.com/104100919/175942058-567e494c-9f19-40b7-b0b3-dc57946043f1.jpg)
After the successfull update to 2.1.6 (all values seem to bee there in the visu) I tried out "Minimal difference to last value" and set this to "1". Now the curve in visu were not so good, I returned to "0" (0 = Abweichungsprüfung deaktivieren).
But it does not work, the values in the memory have been rounded (!), the deactivation ("0") will not work again.
![Verlaufsdaten 270622](https://user-images.githubusercontent.com/104100919/175941512-089862e2-60e7-40f5-9504-b617c1c43608.jpg)
![Instanzeinstellung](https://user-images.githubusercontent.com/104100919/175941515-6035730c-40af-4c84-a82c-9d3b1f1de13f.jpg)

**Comment by Apollon77** [comment]
Does ist work agen whhen you restart the adapter?

**Comment by Apollon77** [comment]
Whichvalue is set in the Defatkt Settings in the instance configuration as minimum difference??

**Comment by Apollon77** [comment]
I need above infos, I can not reporduce the issue

**Comment by sv-hjo** [comment]
if a restart had helped I would not write ....
Minimum difference: 0
loxone sends by example 21.3, object value is ok. The values in the object-overview are right.
But the "Verlaufsdaten" are rounded. This was not the case before.
![value temp](https://user-images.githubusercontent.com/104100919/175946337-b05978a1-1c73-4391-9a41-ac11efa79949.jpg)
![Ausschnitt Debug](https://user-images.githubusercontent.com/104100919/175946339-489442eb-3138-475a-ae98-9fc7c2b549f1.jpg)

**Comment by Apollon77** [comment]
Please show the main adapter instance settings and there the tabs with default balues and also with the general settings

**Comment by sv-hjo** [comment]
![Standardeinstellungen](https://user-images.githubusercontent.com/104100919/175947743-358a0ef9-3cb1-45a5-8419-fa67e8b44fd7.jpg)
![Instanzeinstellungen](https://user-images.githubusercontent.com/104100919/175947746-d36da7aa-25f8-4255-8dea-31efe2af4b6b.jpg)
![history eiinstellungen](https://user-images.githubusercontent.com/104100919/175947747-01974f43-58bf-4390-8c21-8ceb491e289e.jpg)

**Comment by Apollon77** [comment]
Naja die settings sagen "Runden auf 0 stellen". AN der Stelle ist irgendwie eine 0 teingekommen was an sich entweder "leer" ist oder eine andere zahl  drin steht.

Damit wird dann bei der Datenabfrage gerunden - wie gefordert auf 0 stellen  nach dem Komma ... also Nur ganzzahlen.

Also alles wie es soll ...

Aber was war jetzt mit dem "wenn man mal differenz auf was anderes als 0 hatte konnte man nicht zurück ändern? Das ist nicht mehr da? Oder wie?

**Comment by sv-hjo** [comment]
doch klar! seitdem habe ich nur noch die Treppen im Diagramm. 
Ich habe zuerst auf "1" gestellt (zentrale Einstellung im history-Adapter), war mit den "Treppen" in den Kurven dann doch nicht so zufrieden (...) und habe dann wieder auf "0 = Abweichungsprüfung deaktivieren" gestellt.
Seitdem sind die gespeicherten Daten gerundet und ich kann es auch nicht mehr deaktivieren!

**Comment by Apollon77** [comment]
Naj die Treppen liegen aber an den nun gerundeten Werten!

**Comment by Apollon77** [comment]
Normalerweise steht da eine 4 drin oder so .. du musst da mal eine Null reingeschrieben haben

**Comment by sv-hjo** [comment]
klar woher die Treppen kommen.
Die "0" war immer drin. Ich habe die vorhin einmal auf "1" gesetzt, dann ging die ganze Misere los ....
Ich probiere mal mit "4"

**Comment by sv-hjo** [comment]
ändert sich nichts, die Treppen bleiben auch gleich ....
Die "4" macht ja eigentlich keinen Sinn. Wenn ich ALLE Werte haben möchte, dann setze ich doch auf "0". Wie kommt denn der Adapter auf die Idee, im History alle Daten zu ändern? Die Daten müssten doch eigentlich als Rohdaten so bleiben wie sie sind ...

**Comment by Apollon77** [comment]
Und: Runden auf x Stellen gab es vor dem "großen" update nicht und der Default ist "leer" ... Scheinbar ist bei dir da eine 0 reingekommen und die muss da raus

**Comment by sv-hjo** [comment]
ich kann die "0" nicht löschen .... die ist immer drin, in einem Dialog kommt auch eine Fehlermeldung dass das Feld nicht leer sein darf ....

**Comment by sv-hjo** [comment]
"Runden SIe bei Abfrage Zahlen auf" ist leer

**Comment by sv-hjo** [comment]
diese Einstellung hatte ich auch nie verändert. 
Ich hatte in den Standardeinstellungen des Adapters "Minimale Differenz zum letzten Wert" auf 1 gesetzt, nicht mehr!

**Comment by sv-hjo** [comment]
wir können auch gerne das am Telefon durchspielen ... wenn es hilft .... siehe in mein Profil - dort Website ...

**Comment by Apollon77** [comment]
Dann schreib eine 4 rein, das ist am, Ende eh der Default intern. Ich checke es nochmals für neue installationen

**Comment by Apollon77** [comment]
Jupp, Fehler gefunden. Update heute Abend ässt round wieder "leer machen". Danke fürs finden

**Comment by sv-hjo** [comment]
... aber dass die komplette Historie gerundet wird, das ist doch nicht so wirklich im Sinne des Erfinders ....
