### ISSUE TITLE
History data - diagramm hangs

### ISSUE THREAD

**Issue by sv-hjo** [ioBroker/ioBroker.history#186]
I use history with Loxone datapoints. 
There is a bug concerning history and habpanel visualisation. There is an other case open already.
Now the admin-problem:
If I want to see the diagramm of a datapoint (objekts - config - diagramm) there are no datapoints to see, the output "hangs". 
![kein Diagramm](https://user-images.githubusercontent.com/104100919/175815747-b9b6d9d2-1eaa-4033-b5ff-84e58e98d84b.jpg).
admin: 6.1.5
history: 2.1.5
Ingo Fischer analyzed the log for the hisory adapter. I attach it here as well.
[Log history 260622.txt](https://github.com/ioBroker/ioBroker.admin/files/8986688/Log.history.260622.txt)

2022-06-26 12:10:17.086 - objekt diagramm
2022-06-26 12:13:07.318 - visu

**Comment by Apollon77** [comment]
@seebaernd Please install history from Github (important: with npm 6 such an install can take 10 +minutes). Then please provide another such log ... hopefully it works because I found something ... or we should see more

**Comment by seebaernd** [comment]
is there anywhere a short instruction, how to install history adapter from Github on my system? I have never done this before this way.

**Comment by Apollon77** [comment]
Admin - enable Expert mode - Adapter tab will have aan icon "custom install" with a github logo. Click there, then choose in the dialog the "From github" tab. select history, install

**Comment by seebaernd** [comment]
with the history adapter from github it works again :-) Thanks a lot for this greatful help!

![grafik](https://user-images.githubusercontent.com/104657313/180428512-9f1bb699-234a-4bcc-b049-25fd8f2b0166.png)

Some data is missing in the graph. I think this will wirk pretty fine in the future with the fixed adapter.

**Comment by seebaernd** [comment]
do you need actual Logfiles for further analysis?

**Comment by Apollon77** [comment]
No, I will release a fix

**Comment by seebaernd** [comment]
Installed history version 2.2.0 today. Works fine. Thx again.

**Comment by carhe** [comment]
Hi there, thanks a lot for the fix.

Unfortunately, I still have trouble with one datapoint (don't know why this one). For some reason, the diagram skips the measurements of two days (see the attached screenshots). I don't remember exactly, but the 26th could be the day when I updated the history adapter from 2.1.7 to 2.2.0. I attached the history files of this single datapoint, maybe it is helpful.


![screenshot-a](https://user-images.githubusercontent.com/11938966/181694434-85d35609-daca-4765-97ae-31f567ce976f.png)
![screenshot-b](https://user-images.githubusercontent.com/11938966/181694435-94f2cc0b-e06c-4979-845e-7bdde2f34186.png)
![screenshot-c](https://user-images.githubusercontent.com/11938966/181694437-af34ad6c-bcce-4372-98a8-bed44be6bf20.png)
[history.zip](https://github.com/ioBroker/ioBroker.history/files/9216786/history.zip)

.

**Comment by carhe** [comment]
Update: The diagram does not only have problems until 29.07. 00:25, instead this time continuously moves on. Currently it looks like this.

![screenshot-d](https://user-images.githubusercontent.com/11938966/181749359-83637253-a620-4290-9200-ecdc122e53a5.png)

**Comment by carhe** [comment]
Update: Sometimes some values are shown. More than once the first shown value has been the first value of the current day (as in the screenshot). However, I cannot say if this is always the case.

![screenshot-e](https://user-images.githubusercontent.com/11938966/181878785-07ae9db5-08bc-42ea-88cd-945f966154eb.png)
![screenshot-f](https://user-images.githubusercontent.com/11938966/181878844-885c366c-c648-413e-b379-a2c1a517bdc4.png)

**Comment by njdsih** [comment]
Hello, 
since updates to newer Versions i think last week i do have problems with Diagram as well. Values are logged in history adapter properly. But Diagram output is not working normally. Reinstalled history adapter from git with newest version 2.2.0

**Comment by njdsih** [comment]
> Hello, since updates to newer Versions i think last week i do have problems with Diagram as well. Values are logged in history adapter properly. But Diagram output is not working normally. Reinstalled history adapter from git with newest version 2.2.0

I've fixed the diagram by changing history options that only one state per minute is saved. Now the Diagram for me with habpanel works again.

**Comment by Apollon77** [comment]
For Diagram output please check the parameter s... maybe you simply request not enough datapoints but use aggregate none? Why not simply use aggregate=average or such?
