### ISSUE TITLE
-solved- uncomplete graph in Flot with "on change" type since History 2.1.7

### ISSUE THREAD

**Issue by volkergi** [ioBroker/ioBroker.history#187]
hello,
Since History 2.1.7 some graphs dont show in Flot  if "on change" type is used. All other types shows the graph, but the "on change" type is my facourite because this is most exactly.

![Fehler History average](https://user-images.githubusercontent.com/34515612/180625146-bfdbbc9c-09c0-40a2-8c87-f2e69117a224.png)
 
![Fehler History](https://user-images.githubusercontent.com/34515612/180625149-d8e07529-f576-4fa2-8770-1dca339c9bcf.png)

![Fehler History Psolar1](https://user-images.githubusercontent.com/34515612/180625331-ab4784d7-a3cd-4b4b-8679-da6033619c3b.png)

 - Adapter version: 2.1.7
 - JS-Controller version: 4.0.23
 - Node version: 16.16.0
 - Operating system: linux

**Comment by Apollon77** [comment]
Then please enable the enhanced debug log for such a datapoint, then enable debug loglevel for the history instance and load that chart via flot ... then you see what is sent as command to the history adapter for the requerst and some debug.

Most likely the reason is that you sent a rrquest with count=X (or limit=X) and X is just too low to return all values in the given timeframe. In older versions sometimes count/limit was somehow ignored. But in fact needs to be check with a debug log

**Comment by volkergi** [comment]
Thank you for the explain. I have logged the data and i see that values are ignored and values stored. The new values are visible in the graph with both Types "on change" and "average". The old stored values today must also be present, because they are visible in the "average" mode. They are only "lost" in "on change" mode.
![Flot PV average mode](https://user-images.githubusercontent.com/34515612/180835181-fd3be0bf-3874-493a-8a32-fdbf1aea0cae.png)

![Flot PV on change mode](https://user-images.githubusercontent.com/34515612/180835189-f62b3532-a2cc-4dc9-9dfe-4da9ece092e0.png)
.

**Comment by volkergi** [comment]
i checked the Data in history table and see that the data from today are cutted four hours ago. This is the same with the Graph cut at 15:12. Storage retention is one week. When i am waitimg the Data were deleted every time.
It is possible that the problem has something to do with data count in ram?
I have now reduced the value from 960 to 100 and check the graph later again.
![Flot PV History Data](https://user-images.githubusercontent.com/34515612/180837408-8f52a5b8-01ca-4c17-b762-45233e8bd6c7.png)

Also the graph in History doesnt work:
![Flot PV History Data graph](https://user-images.githubusercontent.com/34515612/180838077-2521c623-57b4-4d84-98e2-1042765e93bc.png)

**Comment by volkergi** [comment]
Interesting is the very different data presentation of the 3 day view between "on change" and "average" mode. It seems to be that In the "on change" mode very much data  are not evaluated.

![Flot PV average mode 3 days](https://user-images.githubusercontent.com/34515612/180847292-37ee83f9-bb69-45e2-9e24-d757f8b98f1e.png)
![Flot PV on change mode 3 days](https://user-images.githubusercontent.com/34515612/180847305-37f2cb27-2bc3-4b07-b955-941a048e6c76.png)

**Comment by Apollon77** [comment]
Please do what I have asked for.

When you chose "average" the values are aggregated, so the timeframe is split into X regions with X being count/limit and so the full timeframe is covered by exactly this split of the timeframe into chunks -and getting ONE average value per chunk.

For "on Change" the raw data are returned and so the count is taken into account. What count/limit ou have set? try to increase and you might see a difference ... bit I can only verify with the requested debug logs

**Comment by volkergi** [comment]
The Log was 60MB big and i cannot download it from the broker without crash. I updated the History to 2.2.0 and will see tomorrow again. The integrated chart function in the History Adapter seems to be fixed. Thank you

**Comment by volkergi** [comment]
The issue is also with Version 2.2.0 but not so often. I have no limits in the settings.

![Flot Data](https://user-images.githubusercontent.com/34515612/181361003-a63d09d4-74b0-4985-bdf6-4de332fc5499.png)

I have a problem to log the error because the broken graph is only in the past over more hours. If i log the data for more hours the log file is above 50MB because i have many data points that make many trafic and i cannot download it without crash the Admin. The graph is again only cut with type "on change". I will try to log data with lower data rate to make a smaller log file.

![Fehler History Psolar2 on change](https://user-images.githubusercontent.com/34515612/181359824-ba68e5c3-7eb9-4f10-a971-0c9ae2695ded.png)

![Fehler History Psolar2 average](https://user-images.githubusercontent.com/34515612/181360111-85d1ad85-d074-4d1c-8396-20a16a623d98.png)

**Comment by Apollon77** [comment]
Sorry, but I can only repeat myself. Please send a debug log!

IF flot is not sending a count or limit parameter then defaults are applied by history adapter which is 2000 ... these limits are for "getHistory "requests and can not be seen in any settings

**Comment by volkergi** [comment]
I think i found my problem. I have logged the data over night and see that an other graph is incomplete. If i stretched it in the timeline the data was visible. That means that the data is written by the history adapter but not visible in Flot Adapter. I checked all options and determine that the Aggregate step type was on "counts" and "300". If i make the counts bigger (3000) the graph is complete. I use the Flot adapter for many years but i did not know this point of settings.
Thank you for the support and the development from IOBroker :-)

**Comment by pdbjjens** [comment]
@volkergi @Apollon77 
You saved my day, thank you. I had the same problem with the new history adapter and "on change" graphs. I changed the default in flot from 300 to 3000 as you suggested and miraculously the graph was o.k. again. However, in another graph I had to change the count to even 30000 in order to get a complete graph. I have no idea why, but most important is that my graphs are complete again.

**Comment by Apollon77** [comment]
In fact for queries with "onchange" or "None" aggregates the default "count" is set to 2000 potentially ... (2000 is limit parametr). but yes if 2000 values are too less you need to increase couknt or limit parameter ... This is what I told above already :-)

**Comment by Apollon77** [comment]
I assume solved here?!
