### ISSUE TITLE
index.html fehlt.

### ISSUE THREAD

**Issue by derdoerk** [ioBroker/ioBroker.history#188]
Hallo, 

ich habe das Problem , dass bei mir angezeigt wird, das die index.HTML Datei fehlt

![image](https://user-images.githubusercontent.com/79893009/182036879-9afd0dbb-3072-4309-89d7-b5b3fe68fcee.png)

Ist das ein adapter Fehler oder kann das an meinem System liegen? Ich habe auch andere Versionen Probiert, leider mit immer dem gleich Ergebnis.

Gruß
Dirk

**Comment by Apollon77** [comment]
Nein, die neueste Verison ist nur noch mit Admin 5 zu konfigurieren, wie es auch im Changelog steht
