### ISSUE TITLE
Massive Prozessorbelastung durch History

### ISSUE THREAD

**Issue by MichaelSchaaf999** [ioBroker/ioBroker.history#233]
**Describe the bug**  
Mit laufendem History-Adapter: Massive Prozessorbelastung durch iOBroker.
Ohne laufenden History-Adapter (=pausiert): Normale Prozessorbelastung durch iOBroker.

**Expected behavior**  
normale = nicht übermässige Prozessorbelastung
(ich weiß, wie soll man das definieren)

**Screenshots & Logfiles**  
Mit laufendem History-Adapter / History-Adapter pausiert:
![image](https://user-images.githubusercontent.com/53481090/219936735-17993d18-2f8d-4594-bfa2-bea48b672cf3.png)
1: Mit
2: History-Adapter ausgeschaltet
3: Normale iOBroker-Prozessorauslastung

Daraus schließe ich, dass der History-Adapter den Prozessor massiv auslastet:
Sind vielleicht unsere Einstellungen/Parameter hier bei den Datenpunkten nicht optimal?
Wir haben natürlich sehr viele Datenpunkte, die History aktiviert haben.

**Versions:**  
 - Adapter version: 2.2.4
 - JS-Controller version: 4.0.24 
 - Node version: 14.20.0 
 - Operating system: Debian 4.19.101-1 <os-name>

**Additional context**  
Wenn die Aktivierung von History bei Datenpunkten optimierbar ist: Wo finden wir entsprechende Hinweise zu den Parametern?

**Comment by Apollon77** [comment]
Ich würde zuerst mal vermuten das es "i/o" ist ... also wenn viele Datenpunkte aktiviert sind wiede auch viel geschrieben. Auf was steht "Anzahl datensätze im RAM"? weil so viele werden quasi gesammelt  bevor es auf die Platte geschrieben wird.
Um herauszufinden ob das das Problem ist wäre eine Idee hier mal testweise höhere Werte zu setzen und zu schauen ob dies eine Auswirkung hat. Wobei bei Proxmox (so sieht der Chart ja aus) ggf auch interessant wäre den i/o Chart anzuschauen wie sich dieser verhält wenn der Adapter läuft bzw wenn er nicht läuft. Wenn es i/o ist sollte dies dort sichtbar sein. Die Frage ist auch immer wie oft sich dort Daten ändern - wenn das Datenpunkte mit viele Änderungen sind und so hohe Datenmengen zusammenkommen bitte unbedingt beachten das hier der History-Adapter nicht wirklich optimiert ist für! Bei jedem Update wird immer das GANZE json File neu geschrieben ... 

History ist eher geeignet ein paar Datensätze mit wenigen Änderungen zu historisieren ... alles mehr ist besser bei influxdb oder sql aufgehoben

**Comment by MichaelSchaaf999** [comment]
Danke für die Erläuterungen.
Anzahl Datensätze im RAM: In ca. 50% der Fälle steht dieser Wert auf "10", im Rest der Fälle auf "960" (warum auch immer).

i/o?
Hier mal der Vergleich mit/ohne history mit i/o-Chart:
![image](https://user-images.githubusercontent.com/53481090/220292807-2170a249-41d4-494f-9921-1c5d2febb3db.png)

![image](https://user-images.githubusercontent.com/53481090/220293004-2e46f8c4-2cf8-4cab-9c0e-3b1eddbf0e5a.png)

![image](https://user-images.githubusercontent.com/53481090/220293100-0559d159-3a85-47d2-98bc-a98687da139f.png)

![image](https://user-images.githubusercontent.com/53481090/220293141-a88cfc69-521c-493a-a494-f27a8ba89b18.png)

Bevor ich also ca. 68 mit history.0 laufende Datenpunkte testweise auf höhere Werte beim Parameter "Anzahl datensätze im RAM" setze, wäre m.E. ja der Gedanke, dass history.0 eigentlich gar nicht gut geeignet ist für Datenpunkte mit vielen Änderungen zu verfolgen: Ich hab mir bereits influx.db installiert, es läuft nur noch nicht fehlerfrei.
DAS wäre aber doch dann eher eine sinnvolle Umstellung - sehe ich das richtig?

**Comment by Apollon77** [comment]
> DAS wäre aber doch dann eher eine sinnvolle Umstellung - sehe ich das richtig?

Ja, es wäre aber dennoch vllt sinnvoll mal die RAM datensätze auf 960 (ja das war früherer default ... ich denke du hast irgendwann mal geändert und alle neuen gehen dann auf den ). das sollte das bild massiv verändern

**Comment by Apollon77** [comment]
PS: Wo liegt denn das Datenverzeichnis? Remote auf nem anderen Rechner? Weil das Chart passt eher dazu also "lokal". Wen ja dann verstärkt sich das Problem nochmal weil io-wait dazukommt wegen dem Netzwerk.Write

**Comment by MichaelSchaaf999** [comment]
nein, das Datenverzeichnis liegt nicht auf einem anderen Rechner.

**Comment by MichaelSchaaf999** [comment]
> Ja, es wäre aber dennoch vllt sinnvoll mal die RAM datensätze auf 960 (ja das war früherer default ... ich denke du hast irgendwann mal geändert und alle neuen gehen dann auf den ). das sollte das bild massiv verändern

Verstehe, aber dann sind es pro Datenpunkt bis zu 960 Records, die verloren gehen, wenn das System neu startet? Das will man ja auch nicht.

**Comment by Apollon77** [comment]
Also ja, falls es "spontan rebootet" oder "crasht". Wenn der Adapter beendet wird im Rahmen eines normalen Reboots dann wird das alles geschrieben. Es ginge ja auch erstmal drum zu schauen ob das einen Lasteffekt hat. Danach kannst Du ja "fein tunen"

**Comment by MichaelSchaaf999** [comment]
Kann man eigentlich auch eine SQL-DB auswählen im Datenpunkt? Wenn ja: Was wird empfohlen, MySQL oder andere?

**Comment by MichaelSchaaf999** [comment]
Influxdb (2.0) ist installiert und läuft.
Umstellung von Datenpunkten von history.0 auf influxdb.0 heisst dann aber auch, alle bislang in history gesammelten Daten sind damit weg?

**Comment by Apollon77** [comment]
Also ja auch SQL geht, der Adapter unterstützt MySQL, MSSQL und PostgresQL.

Remote Support für Themen wie InfluxDB ist denke ich nicht sinnvoll möglich bzw abdeckbar.

Für Datenumstellungen der Daten history-> sql/influx ... siehe Readme des History adapters. ist nicht perfekt beschrieben und hatggf fFallstricke ... da aber ggf im Forum melden

**Comment by MichaelSchaaf999** [comment]
- Jetzt hab ich aber nunmal influxdb installiert / installieren lassen.
- Remote Support für die Installation ging ganz gut.
- influxdb 2.0 ist natürlich komplett anders für den Benutzer als denn die alte Version 1.0. (ich sag nur: Client). Aber da will man ja eigentlich auch gar nicht direkt rein, sondern eben mit einem Adapter wie bspw eCharts auf Daten zugreifen. Für die Auswertung und Darstellung.
- Wenn es für die eventuelle Datenmigration nur so etwas gibt wie "nicht perfekt beschrieben" und "Fallstricke", dann werde ich lieber drauf verzichten. Denn daraus noch ein Projekt zu machen, so dass ich da Weihnachten noch dran herumprokele, dass möchte ich dann lieber nicht. Temperaturdaten usw füllen sich dann ja eh wieder neu in influxdb, kommt Zeit, kommt Rat.
- Stelle gerade fest, dass man für Datenpunkte ja die history.0 de-aktivieren kann und influxdb.0 aktivieren kann, dann aber in eCharts doch auch noch die alten Werte aus der history.0 heranziehen kann:
Die Daten stehen anscheinend irgendwo in Dateien, die nicht automatisch gepurged werden, wenn man für einen Datenpunkt die history abschaltet. Das ist für eine Übergangszeit ja auch akzeptabel.
- Dann muss man irgendwann alte Dateien mal löschen? Muss man nur wissen, wo die stehen, denke ich.

**Comment by MichaelSchaaf999** [comment]
Nachtrag:

- alle Datenpunkte, die History aktiviert hatten, umgestellt auf Influxdb.
- Und die influxdb.0-Instanz läuft natürlich.
- History.0-Instanz sodann de-aktiviert.
- Prozessor usw sodann:
<img width="874" alt="image" src="https://user-images.githubusercontent.com/53481090/221126056-8832c243-7a28-4f60-b5b2-efb5b9dfac1a.png">
<img width="878" alt="image" src="https://user-images.githubusercontent.com/53481090/221126132-cdf1db87-a5e6-45d2-b6de-bf8bd43a0af5.png">
<img width="873" alt="image" src="https://user-images.githubusercontent.com/53481090/221126192-280e5c42-f0a5-426e-a0fb-42049ae811c1.png">

Sogar der Netzwerk-Traffic geht dadurch runter.

Ein kleines Problem:
Wenn die history.0-Instanz de-aktiviert ist, werden zwar "alte" eCharts, die noch immer auf history.0-Daten Bezug nehmen, weiter richtig im Aufruf im Browser angezeigt (also ...:8082/vis/index.html?ALF1#ALF1_Strom_eAuto_ZOE)...
![image](https://user-images.githubusercontent.com/53481090/221126495-0ac04796-5d6d-4993-9fb8-6e619fc7199a.png)

Aaaaaber im eCharts-Tab im iOBroker werden die Graphen nicht mehr angezeigt, da "kreiselt" der blaue Balken, weil history.0 dort als Quelle vom Programm entfernt wurde, da de-aktiviert:
![image](https://user-images.githubusercontent.com/53481090/221127648-eb2f7735-813c-499d-8e5c-853273ab903f.png)

Ist vermutlich ziemlich unwichtig, aber ich sag's halt nur.
