### ISSUE TITLE
Blockzeit wird ignoriert

### ISSUE THREAD

**Issue by hgschwibbe** [ioBroker/ioBroker.history#236]
Wie folgendes Screencast-Video zeigt, ignoriert ioBroker.history die Blockzeit.
In dem Video wurde eine Blockzeit von 60 Sekunden eingestellt, im Verlaufsdiagramm sieht man wie fast im Sekundentakt neue Werte gespeichert werden:

https://user-images.githubusercontent.com/1725648/224637075-e8bb6734-b6eb-431f-909a-9c010b192749.mp4

Hier noch ein paar Screenshots:
![grafik](https://user-images.githubusercontent.com/1725648/224638120-b8bdc61f-d34a-464f-a474-df321c1822aa.png)

![grafik](https://user-images.githubusercontent.com/1725648/224638313-2fd4428f-4f02-4310-810d-2604026db29f.png)

Ich Verwende Version v2.2.4 von ioBroker.history

**Comment by hgschwibbe** [comment]
Kleines Update, in eCharts sowie auch in der Diagramm-Ansicht sieht man nur einen Datenpunkt pro Minute, so wie es sein soll. Vielleicht  ein Bug in der Verlaufsdaten-Ansicht?

![grafik](https://user-images.githubusercontent.com/1725648/224640649-a1596bbb-7dc9-47a7-96bb-f6d213144d01.png)

**Comment by Apollon77** [comment]
Ja dies kommt von der Darstellungsoptimierten Speicherung der Daten, Bitte die entsprechende Option diese Opttimierung auszuschalten nutzen und alles ist wie erwartet -> "Optimierte protokollierung übersprungener Werte deaktivieren"

**Comment by hgschwibbe** [comment]
Hat nicht funktioniert.
