### ISSUE TITLE
Werte werden nach Neustart des NAS (IoBroker) erneut gespeichert

### ISSUE THREAD

**Issue by Cele931** [ioBroker/ioBroker.history#244]
Hallo ich habe ein Problem,

Ich habe eine Skript in Blockly welches immer um 22:00 Uhr den Stromverbrauch pro Tag speichert. Diesen Werte speichere ich dann mit history. Doch jetzt das Problem, ich schalte um 23:30 mein NAS aus um Strom zu sparen und starte ihn jeden morgen wieder. In history wird jetzt aber Abends beim herunterfahren eine Null und der gleiche Werte wie um 22:00Uhr nochmals gespeichert. Morgens beim Hochfahren wird nur nochmals der Wert von 22:00 Uhr gespeichert. Somit habe ich jeden Tag drei Werte die ich nicht möchte. Gibt es da einen Trick? habe auch schon versucht über die "Blockzeit" erst wieder zu erlauben einen Wert zu speichern wenn 12h vergangen sind. hat aber nicht funktioniert. 

Danke schonmal für die Hilfe und viele Grüße

**Comment by Apollon77** [comment]
Naja ... schau mal in die Settings und vergleiche was Du beschrieben hast .... was könnte vllt helfen? ;-))

https://github.com/ioBroker/ioBroker.history/blob/master/docs/en/README.md#storage-settings

Tip: "Write NULL values on start/stop boundaries" Setting mal checken?
