### ISSUE TITLE
[Feature request] New aggregation: integral

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.history#25]
By applying the https://en.wikipedia.org/wiki/Trapezoidal_rule one could compute the integral of measured values. A possible application is calculating the total energy used by a device (integral of the power: W => Wh), e.g. https://forum.iobroker.net/viewtopic.php?p=153819#p153819

**Comment by Apollon77** [comment]
Basic implementation maybe using https://www.npmjs.com/package/math-tools

**Comment by AlCalzone** [comment]
When integrating, that module seems to expect a function which has to be defined for all x-values (or time points) in the interval to integrate. We basically only need this simple formula:
```js
// at the start:
integral = 0
// for each data point
integral += 0.5 * (current_value + prev_value) * (current_timestamp - prev_timestamp)
```

**Comment by Apollon77** [comment]
What Time.base we should use? h or min r sec or ms ? :-)  Data-Timestamps has ms, so it would result in "Wms" :-)

**Comment by Apollon77** [comment]
Data aggregation stuff is locate here: https://github.com/ioBroker/ioBroker.history/blob/master/lib/aggregate.js#L65 (For Info)

**Comment by AlCalzone** [comment]
> What Time.base we should use? h or min r sec or ms ? :-) Data-Timestamps has ms, so it would result in "Wms" :-)

As dumb as that sounds for energy consumption, I would use ms to have maximum flexibility. Maybe we can add a scaling factor, which would be 1/3600000 to turn Wms into Wh. Or make the time base configurable?

**Comment by Apollon77** [comment]
Please check out 2.0.0 https://forum.iobroker.net/topic/54197/test-adapter-history-2-0-0
