### ISSUE TITLE
Only enable logging and print to log if the object has actually changed

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.history#26]
See: https://forum.iobroker.net/viewtopic.php?p=156210#p156210

The reason was that the state object was rewritten every time a new measurement came in. The common.history part never actually changed, but history (or in that case sql) picked it up as "enabling" the logging and printed a corresponding output to the log.

I think that can be suppressed by checking if the common.history part of the object in question has changed.

**Comment by Apollon77** [comment]
Hm ... the object should simply not be written each time. What is the reason for this behaviour in the resonsible adapter?

The History Adapter assumes "something changed in config" and so alsoways reinit the logging ... this also includes writing the current value.

Difficult to detect that it was only "updated"

**Comment by AlCalzone** [comment]
I fixed it in the ghoma-adapter on github, but I thought that history might be able to catch this.

> Difficult to detect that it was only "updated"

Don't you have the current settings somewhere co compare with? Or do you always rely on the state object? In the latter case, this is probably not possible without introducing additional overhead. Feel free to close then.

**Comment by Apollon77** [comment]
It is there basically. I will leave it open for later realization :-))
