### ISSUE TITLE
Adapter flutet nach Update den Log mit Fehlern

### ISSUE THREAD

**Issue by Dragon0501** [ioBroker/ioBroker.history#267]
Der History Adapter flutet den Log mit Fehlermeldungen für ganz viele Datenpunkte.

`

 
history.0 | 2023-08-01 21:50:57.773 | error | Cannot store file /opt/iobroker/node_modules/iobroker-data/history/20230801/history.nut.0.output.voltage.json: Error: ENOENT: no such file or directory, mkdir '/opt/iobroker/node_modules/iobroker-data/history/20230801

`

Es werden alle Datenpunkte aufgeführt, dies ist nur eine beispielhafte Fehlermeldung.

Die Meldungen treten regelmäßig auf.
History Adapter ist die 2.2.4
Der Admin ist die 6.6.5

**Comment by Feuer-sturm** [comment]
@Dragon0501 bitte noch die js-controller Version ergänzen und den eingestellten Pfad im History Adapter hier zum Beispiel als Screenshot posten

**Comment by Dragon0501** [comment]
JS-Controller Version 5.0.11

Ein Foto von einem leeren Pfad werde ich nicht hochladen.

**Comment by Apollon77** [comment]
Can you try to downgrade js-controller to eg 5.0.8 or such?

**Comment by Apollon77** [comment]
@Dragon0501 What is set as history path in the adapter config?

**Comment by Dragon0501** [comment]
> @Dragon0501 What is set as history path in the adapter config?

Nothing

**Comment by foxriver76** [comment]
fixed in 2.2.6
