### ISSUE TITLE
Der Adapter möchte in node_modules ein Verzeichnis anlegen

### ISSUE THREAD

**Issue by guergen1** [ioBroker/ioBroker.history#268]
In der Doku steht es wie folgt:
![grafik](https://github.com/ioBroker/ioBroker.history/assets/34395245/46ce7397-d276-4a26-bd57-d97b78b18422)

In meinem Log:
`<html><body>

history.0 | 2023-08-21 14:13:31.748 | error | Cannot  store file  /opt/iobroker/node_modules/iobroker-data/history/20230821/history.device-reminder.2.Wasserkocher.average  consumption.json: Error: ENOENT: no such file or directory, mkdir  '/opt/iobroker/node_modules/iobroker-data/history/20230821'
-- | -- | -- | --
history.0 | 2023-08-21 14:13:27.229 | warn | Data directory /opt/iobroker/node_modules/iobroker-data/history/ does not exist
history.0 | 2023-08-21 14:13:27.191 | warn | Data directory /opt/iobroker/node_modules/iobroker-data/history/ does not exist
history.0 | 2023-08-21 14:13:20.115 | warn | Data directory /opt/iobroker/node_modules/iobroker-data/history/ does not exist
history.0 | 2023-08-21 14:13:20.075 | warn | Data directory /opt/iobroker/node_modules/iobroker-data/history/ does not exist
history.0 | 2023-08-21 14:12:31.051 | warn | Data directory /opt/iobroker/node_modules/iobroker-data/history/ does not exist
history.0 | 2023-08-21 14:11:31.241 | warn | Data directory /opt/iobroker/node_modules/iobroker-data/history/ does not exist
history.0 | 2023-08-21 14:11:31.203 | warn | Data directory /opt/iobroker/node_modules/iobroker-data/history/ does not exist
history.0 | 2023-08-21 14:10:50.856 | warn | Data directory /opt/iobroker/node_modules/iobroker-data/history/ does not exist
history.0 | 2023-08-21 14:10:50.786 | warn | Data directory /opt/iobroker/node_modules/iobroker-data/history/ does not exist
history.0 | 2023-08-21 14:10:26.497 | warn | Data directory /opt/iobroker/node_modules/iobroker-data/history/ does not exist
history.0 | 2023-08-21 14:10:22.066 | error | Cannot parse JSON: undefined
history.0 | 2023-08-21 14:10:21.983 | error | Cannot parse JSON: undefined
history.0 | 2023-08-21 14:09:43.730 | error | Could  not create Storage directory: Error: ENOENT: no such file or directory,  mkdir '/opt/iobroker/node_modules/iobroker-data/history/'

</body>
</html>`

Bitte inder Doku einfügen, dass ein Verzeichnis angelegt werden muss, der Adapter würde es falsch machen, also werden die Daten nicht gespeichert!

**Comment by Apollon77** [comment]
Which js.controller verison? WHich adapter version? What directory is configured?

**Comment by guergen1** [comment]
Version js.controller 5.0.12
Version history-Adapter 2.2.4
NPM: 9.6.7
node.js: 18.17.1

Es ist kein Verzeichnis eingetragen. 
Laut Doku wird dann automatisch das Verzeichnis /opt/iobroker/iobroker-data/history anglegt (s.o.).
Der Adpater versucht allerdings das Verzeichnis  /opt/iobroker/node_modules/iobroker-data/history/ anzulegen, was er natürlich nicht soll und darf laut Doku.
Dadurch kann er natürlich auch nichts drin speichern.
