### ISSUE TITLE
Regression with KNX + history + admin 3.x: Objects of knx.0 can not be enabled for history.0

### ISSUE THREAD

**Issue by Breisgauer** [ioBroker/ioBroker.history#27]
there seems to be an regression with knx adapter and admin 3.x
I reported this issue in https://github.com/ioBroker/ioBroker.knx/issues/30
Please let me know if a translation into english is needed.

**Comment by Apollon77** [comment]
Ich würde erstmal bei Admin anfangen, da Admin downgrade tut.

**Comment by Breisgauer** [comment]
Bestätigt: das Komma in den GA Namen verursacht das Problem. Kommunikation siehe ioBroker/ioBroker.knx#30

Mit ioBroker.admin 2.0.9 tritt das Problem nicht auf, mit ioBroker.admin 3.x schon.
Ein Komma in GA Namen steht meines Wissens nicht im Konflikt mit KNX Richtlinien, insofern gehe ich davon aus, dass viele KNX Projekte ein "Komma" in den Namen haben. Daher wäre es schön, wenn das Problem gefixt werden könnte.
