### ISSUE TITLE
Problem mit "sendTo ("history.0", "storeState"," im Jave script in History Version 1.84

### ISSUE THREAD

**Issue by fr-weyer** [ioBroker/ioBroker.history#28]
Hallo,
die send to History methode funktioniert in meinen Java Scripten nicht mehr seit dem Update auf Version 1.84.
Go back zu Version 1.74 behob das Problem
 
Hier der Code im JAvascript:
sendTo ("history.0", "storeState", {id: ObjEinspeisung5min, state: {
"val": mytempVar,
"ack": 1,
"ts": new Date(JahrAkt + "." + MonatAkt + "." + TagAkt + " " + StundeAkt + ":" + MinuteAkt + ":00").getTime(),
"q": 0
} 
});

Hier die Logs:

history.0	2018-07-02 18:44:10.282	error	message messagebox.system.adapter.history.0 [object Object] Cannot read property 'id' of undefined
history.0	2018-07-02 18:44:10.244	error	at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
history.0	2018-07-02 18:44:10.244	error	at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
history.0	2018-07-02 18:44:10.244	error	at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:233:12)
history.0	2018-07-02 18:44:10.244	error	at Socket.onevent (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:275:10)
history.0	2018-07-02 18:44:10.244	error	at Socket.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
history.0	2018-07-02 18:44:10.244	error	at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemClient.js:52:30)
history.0	2018-07-02 18:44:10.244	error	at Object.change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3398:41)
history.0	2018-07-02 18:44:10.244	error	at Object.message (/opt/iobroker/node_modules/iobroker.history/history.js:146:9)
history.0	2018-07-02 18:44:10.244	error	at processMessage (/opt/iobroker/node_modules/iobroker.history/history.js:225:9)
history.0	2018-07-02 18:44:10.244	error	at storeState (/opt/iobroker/node_modules/iobroker.history/history.js:994:82)
history.0	2018-07-02 18:44:10.244	error	TypeError: Cannot read property 'id' of undefined

**Comment by Apollon77** [comment]
solved with 1.8.5
