### ISSUE TITLE
Null Values are written despite option says not to do so

### ISSUE THREAD

**Issue by Backes89** [ioBroker/ioBroker.history#291]
**Describe the bug**  
Despite configuring the history adapter on the object not to include null/0-values they are saved in my enviroment

**To Reproduce**  
Tag object to save history with the option to ignore null values. They are saved anyway

**Expected behavior**  
No null or zero values

**Screenshots & Logfiles**  
![image](https://github.com/ioBroker/ioBroker.history/assets/31594459/f2f09d71-acca-4073-81a5-2822e48953ad)
![image](https://github.com/ioBroker/ioBroker.history/assets/31594459/0b86c6e8-4bda-4643-bcc2-07765337ef43)

**Versions:**  
 - Adapter version: 3.0.1
 - JS-Controller version: 5.0.16
 - Node version: v18.18.2
 - Operating system: Raspbian
![image](https://github.com/ioBroker/ioBroker.history/assets/31594459/117b9fa4-aa66-45f8-a18d-5cf585c8ed24)

**Comment by Apollon77** [comment]
Ok whats the setting  in the adapter about "write null on start of the adapter" to show where current value s start? If this is activated this would describe why "null" is logged here. Then adjust this setting

**Comment by Backes89** [comment]
Oh man. How dumb am I? Thanks a lot. Didn't saw that setting. Was this newly set to default? Because on my old installation I've never touched that setting ever.

**Comment by Apollon77** [comment]
that was default forever and was made configurable to be allowed to turn off somewhen (also) ages ago :-)
