### ISSUE TITLE
old files should be deleted automatically

### ISSUE THREAD

**Issue by paul53** [ioBroker/ioBroker.history#30]
All my history settings have a storage retention of 2 weeks. Files older than 2 weeks should be deleted automatically, but it does not happen.

Annotation:
My history data is stored in /tmp/history (RAM disk).

**Comment by Apollon77** [comment]
Will check, thanx!

**Comment by paul53** [comment]
Ursache: _bufferChecker_ (alle 10 Minuten Puffer in Datei schreiben) verhindert, dass bei einem nennenswerten Wert "maximale Anzahl Datenpunkte in RAM" die Funktion _checkRetention(id)_ jemals aufgerufen wird.

**Comment by Apollon77** [comment]
I will remove a new version hopefully tomorrow

**Comment by Apollon77** [comment]
release 1.8.7 to npm
