### ISSUE TITLE
Datenübername von history nach influxdb funktioniert nicht

### ISSUE THREAD

**Issue by MSal-RPI4** [ioBroker/ioBroker.history#304]
**Describe the bug**  
Versuche die vergangenen 2 Jahre Iobroker History mit /opt/iobroker/node_modules/iobroker.history/converter/history2db.js in leere InfluxDB zu migrieren.

**To Reproduce**  
Routine über SSH gestartet, mit Resultat gem beigefügter txt:
[20231230_IOB_History2DB_Error.txt](https://github.com/ioBroker/ioBroker.history/files/13798472/20231230_IOB_History2DB_Error.txt)
=> Erster Tag scheint ok ... danach Abbruch.

**Versions:**  
- IOB Adapter Versionen: History: 3.0.1, Influx: 3.2.0
- InfluxDB: v2.7.4
- JS-Controller version: 5.0.17
- Node version: 18.19.0
- Operating system: RPI 4B, 4GB 64Bit Raspbian

**Additional context**  
Retention period im InfluxDB Adapter auf "forever" eingestellt.
History Adapter abgestellt, InfluxDB Adapter läuft.

**Comment by Apollon77** [comment]
I think there is a logging. try to provide the END Date as parameter ... not the start date. he should start always with the oldest files and work up to the provided date.

Does that work?

**Comment by MSal-RPI4** [comment]
I figured that I must have misunderstood ... sorry ;-(.

I have changed to
- pi@iobroker-master:/opt/iobroker/node_modules/iobroker.history/converter $ node history2db.js influxdb.0 info 20231230 /opt/iobroker/iobroker-data/history --processNonExistingValuesOnly

Overall, the migration seems to work pretty well.  However, I just don't understand why the Wolf heating values won't get transferred (have attached the updated "existingDBValues.json" accordingly).

[existingDBValues.json](https://github.com/ioBroker/ioBroker.history/files/13799169/existingDBValues.json)

Is this possibly because of naming convention ?!  Initially, the Zigbee devices did not work either, but they seems to be fine now ?!

**Comment by MSal-RPI4** [comment]
b.t.w., forgot to mention that there are several others which don't transfer either, but I'm less worried about them.

**Comment by MSal-RPI4** [comment]
Has been resolved: After deactivating history logging, reboot and converter re-run over night everything is good ... works like a charm !
