### ISSUE TITLE
retention logic ignores alias(es)

### ISSUE THREAD

**Issue by klassisch** [ioBroker/ioBroker.history#31]
The retention logic seems to ignore alias(es). Bug or feature?

**Comment by Apollon77** [comment]
What exactly you mean? Are there more infos? Reproduction steps?

It may be that it was clear to me 1,5years back bt now not anymore :-( sorry

**Comment by klassisch** [comment]
It is related to a discussion in the forum: https://forum.iobroker.net/post/176842 an the following, e.g. https://forum.iobroker.net/post/176985 

And btw, maybe this https://forum.iobroker.net/post/178760 ff ist still open but no issue created

**Comment by Apollon77** [comment]
ping

**Comment by klassisch** [comment]
Thanks for the reminder.
Yes, I will retest in the ext days with my current system
    Plattform: Windows
    RAM: 7.3 GB
    Node.js: v10.17.0
    NPM: 6.11.3
    JS-controller  3.1.4
    History 1.9.6

**Comment by klassisch** [comment]
Here is a test with the history adapter and alias. 
In my opinion following findings:

1. Entering an alias name but not activating logging will delete the alias name when storing
2. Activiting a "mass subscription" using the blue wrench in the top right corner will delete alle alias names in the elected area

Here is a report in a text editor containing screenshots, logs and notes. I am not sure if this is allowed and good practice but let me try

[iobroker-history-github-isssue-31-tests-by-klassisch-20200705.docx](https://github.com/ioBroker/ioBroker.history/files/4875054/iobroker-history-github-isssue-31-tests-by-klassisch-20200705.docx)

**Comment by Apollon77** [comment]
Ok if it is about that then it is kind of known and an admin topic where an issue exists!

1.) no data are stored when not activated. This is by design
2.) Admin issue exists. 

So then we can close here?

**Comment by klassisch** [comment]
For 2) it is great, that an Admin issue already exists
For 1) "by design" let me add one remark: If I temporarily want to pause the activation by removing the "activate" check, then I also lose the alias name. I guess that this is a consequence of this design decision . Has this also been intended?

**Comment by Apollon77** [comment]
To 2,) if you temporary pause it currently you will loose ALL settings. Not just Alias ... because as soon as you disable it admin will remove it when it is stored. This is that way for all custom properties. Do also here ... admin topic you you want to propose to change this ;-)

**Comment by klassisch** [comment]
ok, thanks for the explanation
