### ISSUE TITLE
History Grafik über FLOT

### ISSUE THREAD

**Issue by markuskobe** [ioBroker/ioBroker.history#42]
History versucht im Bereich "Grafik" über Rickshaw zu zeichnen, was aber aktuell nicht mehr läuft. Könnte das auf FLOT umgestellt werden? Alle Details dazu: https://forum.iobroker.net/topic/11502/history-nur-datenpunkte-keine-grafik/18

**Comment by Ilovegym66** [comment]
bei mir gehts auch nicht, allerdings ein security Error:
`ecurity Error: Content at http://192.168.178.41:81/flot/index.html?range=1440&zoom=true&axeX=lines&axeY=inside&hoverDetail=true&aggregate=onchange&chartType=step&live=30&instance=history.0&l%5B0%5D%5Bid%5D=javascript.0.FritzBoxTraffic.ByteReceiveRateMB&l%5B0%5D%5Boffset%5D=0&l%5B0%5D%5Baggregate%5D=minmax&l%5B0%5D%5Bcolor%5D=%231868a8&l%5B0%5D%5Bthickness%5D=1&l%5B0%5D%5Bshadowsize%5D=1&l%5B0%5D%5Bsmoothing%5D=0&l%5B0%5D%5BafterComma%5D=0&l%5B0%5D%5BignoreNull%5D=false&aggregateType=step&aggregateSpan=300&relativeEnd=now&timeType=relative&noBorder=noborder&bg=rgba(0%2C0%2C0%2C0)&timeFormat=%25H%3A%25M&useComma=undefined&noedit=false&animation=0 may not load data from http://192.168.178.41:8081/#tab-objects.
Load denied by X-Frame-Options: http://192.168.178.41:81/flot/index.html?range=1440&zoom=true&axeX=lines&axeY=inside&hoverDetail=true&aggregate=onchange&chartType=step&live=30&instance=history.0&l%5B0%5D%5Bid%5D=javascript.0.FritzBoxTraffic.ByteReceiveRateMB&l%5B0%5D%5Boffset%5D=0&l%5B0%5D%5Baggregate%5D=minmax&l%5B0%5D%5Bcolor%5D=%231868a8&l%5B0%5D%5Bthickness%5D=1&l%5B0%5D%5Bshadowsize%5D=1&l%5B0%5D%5Bsmoothing%5D=0&l%5B0%5D%5BafterComma%5D=0&l%5B0%5D%5BignoreNull%5D=false&aggregateType=step&aggregateSpan=300&relativeEnd=now&timeType=relative&noBorder=noborder&bg=rgba(0%2C0%2C0%2C0)&timeFormat=%25H%3A%25M&useComma=undefined&noedit=false&animation=0 does not permit cross-origin framing.
`

**Comment by NicoleCollard** [comment]
Ich habe ebenfalls keine gezeichneten Grafiken.

**Comment by davincino** [comment]
Bei mir auch keine Grafik unter dem Datenpunkt. Benutze auch Flot, was über die VIS usw. einwandfrei läuft und Grafiken plottet. Für History wird sql genutzt.

**Comment by RustyThePropellerHead** [comment]
Hello, please have a look at my issue raised @ [iobroker.web](https://github.com/ioBroker/ioBroker.web/issues/29), a work-around to this issue is also provided.

Cheers,
Rusty

**Comment by Apollon77** [comment]
This is when Admin issue
