### ISSUE TITLE
Store data of today into a RAM disk

### ISSUE THREAD

**Issue by paul53** [ioBroker/ioBroker.history#44]
Aufgrund der Tatsache, dass jeden Tag ein neuer Ordner für die Speicherung der aktuellen Daten erzeugt wird, halte ich es für eine gute Idee, den aktuellen Ordner in einer RAM-Disk (tempfs) zu erstellen und den Ordner vom Vortag von der RAM-Disk in den Flash-Speicher zu verschieben. Für den Lesezugriff könnte ein Symlink auf den Ordner der RAM-Disk erzeugt werden.
Grund: Die Schreibbelastung des Flash-Speichers würde dramatisch sinken.

Bei Stop(kill) der History-Instanz müsste der aktuelle Ordner von der RAM-Disk auf den Flash-Speicher kopiert werden, um bei History-Start wieder in die RAM-Disk verschoben zu werden.

**Comment by Apollon77** [comment]
very specific feature request ... I see especially a problem if the server is rebootet or crashes and so you will loose data

**Comment by paul53** [comment]
Bei Reboot sehe ich kein Problem, wenn bei Kill der Transfer von der RAM-Disk zum Flash erfolgt und bei Instanz-Start umgekehrt.

**Comment by Apollon77** [comment]
Sure reboot is "clean", crash/kernel panic/bad power stuff (and we hve many users with such HW/Power related problems and crashes) would mean data loss

**Comment by paul53** [comment]
Ein Hinweis, dass bei Crash/Power loss (keine USV) die Daten in der RAM-Disk verloren sind, sollte genügen. Die RAM-Disk für die aktuellen Daten sollte optional sein (ohne Pfadangabe auf tempfs keine RAM-Disk).

**Comment by n3roGit** [comment]
Nice idea

**Comment by Apollon77** [comment]
Am Ende ist das bereits möglich. Du definierst jetzt bereits wieviele Datenpunkte im Speicher gehalten werden. Ist in der Konfig drin. Schreib da 10000 rein und es werden die letzten 10k States im Ram gehalten und erst gespeichert wenn voll oder wenn er beendet wird. Also von daher geht das quasi schon
