### ISSUE TITLE
| is forbidden in filenames in Windows

### ISSUE THREAD

**Issue by Stabilostick** [ioBroker/ioBroker.history#49]
Include the complete ioBroker character filterlist into history-adapter. Add the "\u0000 : / |"-characters.

\u0000:/|*,;'"`<>\?

https://github.com/ioBroker/ioBroker.history/blob/0223200829dd564c5f096678581921754a130475/lib/getHistory.js#L41

**Comment by Apollon77** [comment]
will come in 1.9.0
