### ISSUE TITLE
minmax liefert falsche Werte

### ISSUE THREAD

**Issue by Hirsch-DE** [ioBroker/ioBroker.history#54]
Sollte die Antwort auf eine Auswertung wirklich so aussehen?
Die Optionen sind als Zeitraum genau ein Jahr mit Intervall ein Jahr.
Erster Wert die Temperatur, zweiter Wert der Zeitstempel.

13:44:26.384 | info | javascript.0 script.js.test: 17   2018-07-28T11:44:23.203Z
13:44:26.385 | info | javascript.0 script.js.test: 17   2018-09-12T21:40:00.011Z
13:44:26.386 | info | javascript.0 script.js.test: -6.5   2019-01-22T04:40:04.792Z
13:44:26.386 | info | javascript.0 script.js.test: 39.6   2019-06-30T14:25:08.583Z
13:44:26.387 | info | javascript.0 script.js.test: 30.2   2019-07-28T11:30:43.063Z
13:44:26.388 | info | javascript.0 script.js.test: 30.2   2019-07-28T11:44:23.203Z

bei nur min lautet die Antwort so:

13:47:02.206 | info | javascript.0 script.js.test: -6.5   2018-07-28T11:47:00.837Z
13:47:02.206 | info | javascript.0 script.js.test: -6.5   2019-01-26T23:47:00.837Z
13:47:02.207 | info | javascript.0 script.js.test: -6.5   2019-07-28T11:47:00.837Z

Im Flot wird mir als minmax auch nicht die richtigen Werte angezeigt.

**Comment by Apollon77** [comment]
Was genau ist denn in deinen Augen falsch? Ohne Dir echten Basisdaten ist das extrem schwer zu sagen. Oder ist deine Frage warum es so viele Werte als Ergebnis sind?
Das würde an Minmax als aggregation liegen Undings Absicht weil minmax für die grafische Darstellung optimiert ist.

**Comment by Hirsch-DE** [comment]
Wie sollten die Daten denn geliefert werden?


Am 28. Juli 2019 15:22:52 MESZ schrieb Ingo Fischer <notifications@github.com>:

**Comment by Apollon77** [comment]
Minmax aggregiert bestimmte zwischenwerte für eine bessere/genauere Darstellung und versucht damit min und Max werte des aggregierungszeitraumsdarzustellen. 

Die echten Werte kommen mit aggregation none.

**Comment by Hirsch-DE** [comment]
Bei min kann ich die Werte verstehen.
1. Beginn der Auswertung
2. Der min-Wert für den Zeitraum
3. Ende der Auswertung
Hier stimmt aber der min Wert immer überein, auch die Zeitstempel ts

Bei minmax kann ich die Zeitstempel überhaupt nicht verstehen, wie diese zustande kommen?

Für beide Abfragen sind die gleichen Optionen verwendet.

**Comment by Apollon77** [comment]
DIe Zetstempel entstehen weil es für die Grafische Darstellung optimiert ist.

Code: https://github.com/ioBroker/ioBroker.history/blob/master/lib/aggregate.js#L78 Und https://github.com/ioBroker/ioBroker.history/blob/master/lib/aggregate.js#L118
