### ISSUE TITLE
Nur aktueller Tag

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.history#71]
v1.9.9

Hallo, ich schaue mir grad die History Tabelle am Leistungsobjekt eines Messsensors an und sehe die Änderungen vom heutigen Tag. Nun hab ich versucht das Datum von gestern einzutragen .. und beim Betätigen des Refresh buttons passierte gar nichts .. die Werte von heute sind nicht mal verschwunden. Fenster verlassen und nochmal rein .. irgendwann stand da "no data". Beim schreiben dieses Textes purzeln Werte von heute ein obwohl im Filter noch immer das Datum von gestern eingetragen ist. Dies nur als Kontext .. wenn das Verhalten grundsätzlich normal ist .. ok.

ABER .. ich warum sehe ich keine Daten von gestern? Hatte das Problem auch schon beim FBpresence-Adapter .. dass dort immer behauptet wurde es gäbe keine historischen Daten. Retention Time steht alles auf Default .. 1 Year.

Help!

**Comment by Apollon77** [comment]
Du nutzt hier Admin um das zu tun? Da gibt es scheinbar ein issue das da der Filter nicht geht. Am besten nutze direkt flit oder so um die Daten anzusehen in Charts.

**Comment by daniel-lo** [comment]
Schade, bin gerade dort hin gewechselt, weil ich mit der Flot-Anzeige nicht so gut zurecht komme :-(

**Comment by daniel-lo** [comment]
Keine Ahnung was da los ist .. jetzt sehe ich in besagter Tabelle nicht mal mehr die Daten von heute :-(

**Comment by Apollon77** [comment]
Ja es gibt dazu ein Admin issue sorry.

**Comment by daniel-lo** [comment]
hast du eine nummer für mich .. damit ich das subscriben kann?

**Comment by Apollon77** [comment]
Finde nur das https://github.com/ioBroker/ioBroker.admin/issues/410 ... also mit details ggf neues issue anlegen. Am besten mit genauen Infos und Screenshots.
