### ISSUE TITLE
Vollständige Anleitung zur Migration von History Daten auf InfluxDB

### ISSUE THREAD

**Issue by mitsol** [ioBroker/ioBroker.history#75]
Man findet in der Readme eine Anleitung zur Umstellung von ioBroker History auf InfluxDB: https://github.com/ioBroker/ioBroker.history/blob/master/docs/de/README.md#history-daten-in-sql-oder-influxdb-%C3%BCbernehmen

Vielen Dank für die detaillierte Anleitung. Leider fehlen mir für mein Verständnis ein paar Infos: Kann man hier noch genauer ergänzen, welche Schritte nötig sind, um ein System mit bestehender History (in Files) in die InfluxDB zu migrieren, wenn die InfluxDB gerade neu installiert wurde, aber die History-Files schon bestehen? - Initial ist die neue Influx Datenbank leer, somit werden keine Analysetools benötigt. Es müssten einfach alle Daten in die neue InfluxDB gespielt werden. 

Es geht außerdem bei der Anleitung nicht klar hervor, ob man die Instanzen (History, InfluxDB) beim Ausführen des Scripts zum Migrieren deaktivieren muss oder ob man vl sogar den gesamten ioBroker Dienst deaktivieren soll? 

Des weiteren frage ich mich, ob ich nach dem Migrieren alle History-Objekte einzeln öffnen und für History deaktivieren und für InfluxDB aktivieren muss oder ob es hier auch eine Möglichkeit gibt, jedes History-Objekt von File-basierter Speicherung auf InfluxDB umzustellen.

Vielen Dank

**Comment by Apollon77** [comment]
Um ehrlich zu sein kann ich Dir die meisten Fragen nicht beantworten. Ich habe die Skripte vor en paar Jahren mal erstellt weil ich es selbst brauchte. Ich fürchte Du musst hier etwas experimentieren.Ich schreibe mal ein paar Infos die ich denke so sind:
* Ja wenn alles leer ist dann musst du keine Analyse fahren. Die sollte ignoriert werden
* History am besten stoppen (das nicht neue Daten dazwischen schiessen, aber Influxdb muss laufen weil die Daten sonst nicht rein kommen. 
* Der Adapter zieht nur Daten um, heisst: Deaktivieren in History bzw Aktivieren in Influxdb musst Du manuell tun

Wenn Du es rausfindest dann wöre ein PR bzw infos zu Änderungen für die Doku super. Danke

**Comment by daNick73** [comment]
Vielen Dank für die Arbeit.

In der Anleitung ist ein Fehler

> Verwendung: nodejs history2db.js [DB-Instanz] [Loglevel] [Date-to-start|0] [path-to-Data] [delayMultiplicator] [--logChangesOnly [relog-Interval(m)]] [--ignoreExistingDBValues] [--processNonExistingValuesOnly] [--processAllDPs] [--simulate]
> 
> Beispiel: nodejs history2influx.js influxdb.0 info 20161001 /path/to/data 2 --logChangesOnly 30 --processNonExistingValuesOnly

Im Beispiel wird der falsche Name des Scripts verwendet (...2influx.js, statt ...2db.js)

Gruß Nico

**Comment by nicomania** [comment]
Hallo @Apollon77, danke für die Arbeit! Leider kann ich unter allen einschlägigen links oder in meiner Installation keines der genannten Skripte finden. Wo kann man diese noch runterladen? Oder gibt es mittlerweile einen aktuelleren Weg/Tool/Adapter, um seine Daten von history nach InfluxDB umzuziehen?
Vielen Dank!

**Comment by Apollon77** [comment]
Skripte sind in /opt/iobroker/node_modules/iobroker.history/converter wie auch unter https://github.com/ioBroker/ioBroker.history/blob/master/docs/en/README.md#migrate-history-data-to-sql-or-influxdb beschrieben

**Comment by nicomania** [comment]
> Skripte sind in /opt/iobroker/node_modules/iobroker.history/converter wie auch unter https://github.com/ioBroker/ioBroker.history/blob/master/docs/en/README.md#migrate-history-data-to-sql-or-influxdb beschrieben

ok, danke, habs gefunden. Hatte nicht unter node_modules geschaut. Ein "find" hat die skripte leider auch nicht gefunden.
