### ISSUE TITLE
History Adapter - NAS Drive smb 3.1.1

### ISSUE THREAD

**Issue by SCoe2k** [ioBroker/ioBroker.history#77]
<img width="573" alt="Bildschirmfoto 2020-08-05 um 17 41 11" src="https://user-images.githubusercontent.com/49205209/89510866-73d99f00-d7d1-11ea-9b5a-c55c4fba239c.png">
In the past I mounted my network drive via smb1. This worked perfectly and I could write all the history data to the mapped drive.

I changed to smb 3.1.1
I can reach the mapped drive via ssh and for example backup Adapter can write on NAS.
History adapter will not write on NAS. It creates the folder of the day and creates only ZERO byte files. The error log states read/write errors.
Any idea? Is history able to read/write from mounted smb 3 drives?

Mounting via fstab: 
//192.168.1.1/Luftiger-SG/4TB_HDD_SG/Smarthome/iobroker/Data /media/Luftiger_iobroker_Data cifs credentials=/home/pi/.smbcredentials,vers=3.1.1,uid=1000,gid=1000,rw,dir_mode=0777,file_mode=0777,x-systemd.automount,x-systemd.requires=network-online.target 0 0

![6](https://user-images.githubusercontent.com/49205209/89500681-69fc6f80-d7c2-11ea-85b2-9392c8f62c48.jpg)
![5](https://user-images.githubusercontent.com/49205209/89500683-6bc63300-d7c2-11ea-8408-b8c202c2b833.jpg)
![4](https://user-images.githubusercontent.com/49205209/89500687-6c5ec980-d7c2-11ea-8546-031e18c5065d.jpg)
![3](https://user-images.githubusercontent.com/49205209/89500692-6cf76000-d7c2-11ea-918f-c39bfc6aeb2a.jpg)
![2](https://user-images.githubusercontent.com/49205209/89500695-6cf76000-d7c2-11ea-9c5c-805fa82f2ee7.jpg)
![1](https://user-images.githubusercontent.com/49205209/89500697-6d8ff680-d7c2-11ea-95f4-83ba57fb725a.jpg)

**Comment by Apollon77** [comment]
is the iobroker user allowed to write and read there?
In fact the history adapter uses normal file operations to read/write and so it is unimportant if samba or nfs or direct hdd/ssd ...

**Comment by SCoe2k** [comment]
I am not an expert, but my understanding is that with privileges 0777 everyone is allowed to read and write.

**Comment by Apollon77** [comment]
Sollte, ja. Gibt es in /var/log/syslog weitere Infos?

**Comment by SCoe2k** [comment]
Folgende Infos sind in der syslog zum Zeitpunkt der Schreibversuche:Aug  7 10:40:33 raspi04 kernel: [27619.393220] 
cifs_all_info_to_fattr: 15 callbacks suppressed
Aug  7 10:40:33 raspi04 kernel: [27619.393223] CIFS VFS: bogus file nlink value 0
Aug  7 10:40:33 raspi04 kernel: [27619.406102] CIFS VFS: bogus file nlink value 0
Aug  7 10:40:33 raspi04 kernel: [27619.440048] CIFS VFS: bogus file nlink value 0
Aug  7 10:40:33 raspi04 kernel: [27619.492926] CIFS VFS: bogus file nlink value 0
Aug  7 10:40:33 raspi04 kernel: [27619.526104] CIFS VFS: bogus file nlink value 0
Aug  7 10:40:33 raspi04 kernel: [27619.560360] CIFS VFS: bogus file nlink value 0
Aug  7 10:40:33 raspi04 kernel: [27619.620848] CIFS VFS: bogus file nlink value 0
Aug  7 10:40:33 raspi04 kernel: [27619.663128] CIFS VFS: bogus file nlink value 0
Aug  7 10:40:33 raspi04 kernel: [27619.676561] CIFS VFS: bogus file nlink value 0
Aug  7 10:40:33 raspi04 kernel: [27619.714122] CIFS VFS: bogus file nlink value 0
