### ISSUE TITLE
Filter and history download do not work as expected

### ISSUE THREAD

**Issue by MartinSchlender** [ioBroker/ioBroker.history#78]
In the history of an object there is a way to filter. One can enter date from to and time from to. The result is unpredictable. With German date format it is not working at all. With american date format it works sometimes.

![image](https://user-images.githubusercontent.com/69381774/89704904-ca251a00-d958-11ea-8e5a-99e3385751bb.png)

Adapter version is 1.9.10

**Comment by Apollon77** [comment]
This is an admin issue. Please search there or make new one
