### ISSUE TITLE
retrieve all history values

### ISSUE THREAD

**Issue by matze-dev** [ioBroker/ioBroker.history#79]
**Is your feature request related to a problem? Please describe.**
I want to retrieve all history values. Unless I can only get 3 days in the past. I want get all values.

**Describe the solution you'd like**
Please tell me which start value I have to use 0 or -1 is expected to get all values.
The end value could be empty or both values can be empty. Please consider this case in documentation.

**Comment by Apollon77** [comment]
How exactly you try it?

**Comment by matze-dev** [comment]
Hi Ingo,
I use this code, but only get 3 days back.

sendTo('history.0', 'getHistory', {
    id: my_id,
    options: {
        start: 	   0,
        end:       new Date().getTime(),
        ignoreNull: true,
        aggregate: 'none'
    }
}, function (result) ...

**Comment by Apollon77** [comment]
Please make sure to also set "count" key ... else it is limited to 500 returned values!
