### ISSUE TITLE
getHistory liefert nur daten von heute

### ISSUE THREAD

**Issue by inidona** [ioBroker/ioBroker.history#80]
aktuelle Installation:
Mein Code
   var end = Date.now() - (60 * 1000  * 60 * 13 );
    var start = end - ( 60 * 1000 * 3 )
    log (""+new Date(start).toUTCString())
    log (""+new Date(end).toUTCString())
    
        sendTo('history.0', 'getHistory', {
          id: id,
          options: {
              start:      start,
              end:        end,
              aggregate: 'none'
          }
        }, function (result) {

liefert nur Daten wenn die Ende Zeit noch heute ist. Sobald das Zeitfenster auf gestern liegt kommt nichts mehr.
Wenn ich die Daten in Flot ansehe sind sie vorhanden.

danke
Andreas

**Comment by Apollon77** [comment]
Please try to set "count". If not set the method only returns 500 entries. Can this be the reason?
