### ISSUE TITLE
Delta Prüfung für Delta kleiner 1

### ISSUE THREAD

**Issue by JanSHUP** [ioBroker/ioBroker.history#81]
Wenn ich die Einstellungen der Deltaprüfung richtig verstehe sind für Delta nur Werte größer 1 vorgesehen.

Bei meiner Applikation bekomme ich Temperaturmesswerte inklusive zwei Nachkommastellen vom Sensor, die gerade auf der letzten Nachkommastelle stark springen.

Wenn ich die Deltaprüfung richtig verstehe würde eine 1 einem Runden auf Integerwerte gleichkommen.
Die erste Nachkommastelle bzw. 0,5°C Schritte würden mich schon interessieren. Ist es möglich bei der Deltaprüfung auch Delta <1 zu erlauben?

Dankeschön, Jan

**Comment by Diginix** [comment]
Ich hab da bisher immer frech 0,1 eingetragen. Aber im Tooltip steht tatsächlich dass nur ganzzahlige Werte funktionieren.
![image](https://user-images.githubusercontent.com/39678667/98360071-8316f580-2029-11eb-8c16-a3983bdae4b6.png)

Wäre also ein sinnvoller feature request.

**Comment by Apollon77** [comment]
AN sich sollte 0.1 tun

**Comment by Diginix** [comment]
Im RAW steht auch minDelta 0.1, aber in den Admin History Settings wird es zu es mit Komma ausgegeben.
Trotz 0.1 erhalte ich History Werte mit Änderungen nur der 2 Nachkommastelle:
![image](https://user-images.githubusercontent.com/39678667/98362673-f6bb0180-202d-11eb-87f5-37666402680f.png)

**Comment by Apollon77** [comment]
wie sieht die komplette konfig des datenpunkts aus?

**Comment by Apollon77** [comment]
PS: In den Adapter tests ist ei test mit 0.5 als "changesMinDelta" drin und daher wird das an sich getestet ... strange

**Comment by Diginix** [comment]
`"history.0": {
  "enabled": true,
  "changesOnly": true,
  "debounce": "1000",
  "maxLength": "100",
  "retention": "0",
  "changesRelogInterval": 0,
  "changesMinDelta": 0.1,
  "aliasId": ""
},`

**Comment by Apollon77** [comment]
Then it would be great to see a debug log ... ideally just the part for a "change smaller then delta" :-) A Debug log shows relatively good why  things are logged ... and I have  an idea already ;-)

**Comment by JanSHUP** [comment]
Where / How can I enable debugging or see the detailed debug messages? 
In IO Broker - Log and IO Broker - Events I can't find any entries about these changes.

**Comment by Diginix** [comment]
@JanSHUP 
here you have to change the log level to debug for the history instance:
![image](https://user-images.githubusercontent.com/39678667/99077907-c9d29580-25bd-11eb-9371-8a3a61185fa6.png)

**Comment by JanSHUP** [comment]
RAW Variable:
{
  "from": "system.adapter.mqtt.0",
  "user": "system.user.admin",
  "ts": 1604525622437,
  "common": {
    "name": "/ESP-Temperaturmessung/temperatur",
    "role": "variable",
    "desc": "mqtt server variable",
    "type": "string",
    "write": true,
    "read": true,
    "custom": {
      "history.0": {
        "enabled": true,
        "changesOnly": true,
        "debounce": "1000",
        "maxLength": "9000",
        "retention": "31536000",
        "changesRelogInterval": "6000",
        "changesMinDelta": 0.5,
        "aliasId": ""
      }
    }
  },
  "native": {
    "topic": "/ESP-Temperaturmessung/temperatur"
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "mqtt.0.ESP-Temperaturmessung.temperatur",
  "type": "state"
}
Log: 
![todelete1](https://user-images.githubusercontent.com/68033045/99079629-7e6db680-25c0-11eb-840f-85378ed2193b.jpg)
Variable table: 
![todelete2](https://user-images.githubusercontent.com/68033045/99079804-b8d75380-25c0-11eb-9225-9bf22f52b26e.jpg)

I changed debug level recently and added "add source" in history properties

**Comment by Apollon77** [comment]
And whats now the issue? Log and other screenshort do not really match ...

**Comment by JanSHUP** [comment]
You are right. I cannot reconstruct the issue with my recent settings.
Probably the history adapter is fine.
thanks anyway.
PS: maybe you can change the tooltip information in the next version. It says only values equal to or above 1 are valid.
