### ISSUE TITLE
Konfigseite öffnet nicht mehr

### ISSUE THREAD

**Issue by derLaas** [ioBroker/ioBroker.history#84]
Leider klappt das Menü zum konfigurieren der History-Einstellung nicht mehr auf.

Ich vermute, dass die 3 Storage-Optionen: History, awattar und sourceanalytix sich hier gegenseitig behindern, keiner dieser öffnet sich mehr nach dem drauf klicken.

![Screenshot 2020-12-12 at 21 48 36](https://user-images.githubusercontent.com/75912140/101994602-e4368680-3cc3-11eb-8e56-b6fe87678c1d.png)

vielleicht gibt es eine Chance, dass ihr das nachstellen könnt?! Braucht ihr noch weitere Daten von mir?

beste Grüße
Lars

**Comment by Apollon77** [comment]
Fehler ist in awattar ... https://github.com/sirjojo69/ioBroker.awattar/blob/master/io-package.json#L55 ... aber kein Custom_m.html
