### ISSUE TITLE
history.0 terminated by request of the instance itself

### ISSUE THREAD

**Issue by Scotty-89** [ioBroker/ioBroker.history#85]
Hallo zusammen,
ich bekomme jetzt immer mal wieder diese meldungen, leider kann ich damit weniger was anfangen...
kann mir hier jemand helfen ? 

host.iobroker | 2021-01-13 19:06:26.672 | error | instance system.adapter.history.0 terminated by request of the instance itself and will not be restarted, before user restarts it.
-- | -- | -- | --
history.0 | 2021-01-13 19:06:26.157 | warn | (2839) Got terminate signal. Checking desired PID: 2854 vs own PID 2839

**Comment by Apollon77** [comment]
Da braucht es ein bissl mehr log drum herum. Dieser Fehler passiert wenn ein Prozes snoch läuft, der js.controller aber denkt es sollte ein anderer sein - dann wird einer aufgefürdert sich zu beenden (der falsche) und der beendet sich. heisst: was passiert denn "aussen rum" das da sowas ist
