### ISSUE TITLE
Question: History Daten im Javascript

### ISSUE THREAD

**Issue by Streit187** [ioBroker/ioBroker.history#92]
Hallo, 
ich möchte gerne von einem Datenpunkt den Durchschnitt der History Werte jeden Tag von 0 Uhr bis jetzt in einen weiteren Datenpunkt schreiben. 
Mit dem folgenden Skript funktioniert das auch mit einem festen Unix Timestamp als Startpunkt. Dieser müsste aber variabel "Heute 0 Uhr" sein und ich konnte nicht herausfinden wie sich das umsetzen lässt. 
Ich hoffe mir kann hier jemand helfen. 

`//Autarkie Heute
var end = Date.now();

createState('0_userdata.0.Solar.AutarkieHeute');
sendTo('history.0', 'getHistory', {
    id: '0_userdata.0.Solar.Autarkie',
    options: {
        start:      1614556801,
        end:        end,
        aggregate: 'average',
    }
}, function (result) {
    for (var i = 0; i < result.result.length; i++) {
        setState('0_userdata.0.Solar.AutarkieHeute', (result.result[i].val), true);
    }
});`

**Comment by Apollon77** [comment]
Ich denke so eine "usage frage" wäre wher was fürs Forum.

am Ende ist es (und das ist nur die Richtung!) mit "new Date()" ebkommst Du ein Date Object. das kannst du dann ändern (https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Date) und mit "getTime()" kannst Du diese "Zahl" bekommen die jetzt hart drin steht

**Comment by Diginix** [comment]
Evtl. auch mal den statistics Adapter anschauen. Der bietet genau das ohne dass Werte parallel per history persistiert werden müssen.
